"""Custom environments. Importing this package registers them with Gymnasium.

The trainer does `import bestiary.envs` for this side effect, after which
`gym.make("Spyder-v0")` works exactly like a built-in env id.

Two robots, each in a flat world and a desert one:

    Spyder-v0 / SpyderDesert-v0    12-DoF spider (assets/spyder12*.xml)
    Hound-v0  / HoundDesert-v0     16-DoF wheel-legged dog (assets/hound16*.xml,
                                   generated by bestiary.robots.hound.build)

In both pairs the robot subtree is identical between the flat and desert
model, so the observation and action spaces match and a flat-world checkpoint
loads on the desert unchanged.
"""
from gymnasium.envs.registration import register, registry

from bestiary import paths

if "Spyder-v0" not in registry:
    register(
        id="Spyder-v0",
        entry_point="bestiary.envs.spyder:SpyderEnv",
        # Truncation horizon: episodes end after 1000 steps (50 seconds at
        # 20 Hz) even if the spider is still healthy — same as Ant-v5.
        max_episode_steps=1000,
    )

if "Hound-v0" not in registry:
    register(
        id="Hound-v0",
        entry_point="bestiary.envs.hound:HoundEnv",
        # 1000 steps at 20 Hz = 50 s, same horizon as every other env here.
        max_episode_steps=1000,
    )

if "HoundDesert-v0" not in registry:
    register(
        id="HoundDesert-v0",
        # Same env class, same spaces — only the world XML differs, so a
        # Hound-v0 checkpoint loads here unchanged.
        entry_point="bestiary.envs.hound:HoundEnv",
        kwargs={"xml_file": str(paths.HOUND_DESERT_XML)},
        max_episode_steps=1000,
    )

if "HoundPD-v0" not in registry:
    register(
        id="HoundPD-v0",
        # Same env class and same 16-slot action vector as Hound-v0. The model
        # differs only in actuator type: the twelve leg joints are position
        # servos, so an action is a target angle offset from the standing
        # stance rather than a torque. The env reads which it is off the model.
        entry_point="bestiary.envs.hound:HoundEnv",
        kwargs={"xml_file": str(paths.HOUND_PD_XML)},
        max_episode_steps=1000,
    )

if "HoundPDDesert-v0" not in registry:
    register(
        id="HoundPDDesert-v0",
        entry_point="bestiary.envs.hound:HoundEnv",
        kwargs={"xml_file": str(paths.HOUND_PD_DESERT_XML)},
        max_episode_steps=1000,
    )

if "HoundPDTrackDesert-v0" not in registry:
    register(
        id="HoundPDTrackDesert-v0",
        # SAME robot, SAME model XML and SAME 169-wide observation as
        # HoundPDDesert-v0 — only the reward differs, and the three
        # command_reserved slots stop being zero. A different env CLASS rather
        # than a kwarg because the reward is structurally different, not
        # retuned: `research/learnings/004` is the record of what it costs to
        # treat those two as the same kind of change.
        entry_point="bestiary.envs.hound_track:HoundTrackEnv",
        kwargs={"xml_file": str(paths.HOUND_PD_DESERT_XML)},
        max_episode_steps=1000,
    )

if "SpyderDesert-v0" not in registry:
    register(
        id="SpyderDesert-v0",
        # Same env class, same spaces — only the world XML differs (desert
        # heightfield instead of the plane), so Spyder-v0 checkpoints load
        # here unchanged. Terrain files come from bestiary.terrain.generate.
        entry_point="bestiary.envs.spyder:SpyderEnv",
        kwargs={"xml_file": str(paths.SPYDER_DESERT_XML)},
        max_episode_steps=1000,
    )
