"""Hound-v0: a 16-DoF wheel-legged robot dog (Ant-v5 recipe, wheeled morphology).

The repo's second hand-built environment. Structurally it is Spyder-v0 again —
same reward terms, same upright termination, same terrain-aware health check —
so results stay comparable. What is new is the fourth joint on every leg:

    4 legs x (abduction + hip + knee + WHEEL) = 16 actuated DoF

The model is generated by robots/hound/build.py (assets/hound16.xml, and
assets/hound16_desert.xml for the desert heightfield), dimensioned from
Unitree Go2's published link lengths and link masses with a hub-motor wheel
where Go2's point foot would be. Read that file's docstring for the mechanics;
this one covers what the wheel does to the *learning problem*.


ACTION SPACE -- Box(-1, 1, (16,))
    One float per motor, in per-leg blocks of four, legs ordered FL, FR, RL,
    RR (the XML <actuator> block is the contract; robots/hound/check.py asserts it):

        [FL_abduct, FL_hip, FL_knee, FL_wheel,  FR_..., RL_..., RR_...]

    WHAT A MAGNITUDE MEANS DEPENDS ON THE MODEL. Both are Box(-1, 1, (16,))
    with the same slots in the same order; only the twelve leg entries change
    meaning. The env reads which it is off the model's actuator types, so they
    cannot disagree — see `action_to_ctrl`.

    Hound-v0 / HoundDesert-v0  (<motor>, assets/hound16*.xml)
        A fraction of that motor's peak torque. The peaks are NOT uniform:
        23.7 N*m at abduction and hip, 40 at the knee, and only 3.0 at the
        wheel. That last one is not a typo and not timidity — a wheel carrying
        4.25 kgf breaks traction at 3.19 N*m, so a bigger wheel motor would
        buy wheelspin and nothing else. The leg motors are sized by what they
        must hold; the wheel motors by what the ground will accept.

    HoundPD-v0 / HoundPDDesert-v0  (<position>, assets/hound16pd*.xml)
        For the twelve LEG entries: a target angle, as an offset from the
        standing stance, scaled by Spec.action_scale = 0.5 rad. So 0.0 asks
        the joint to stay at its standing angle and +/-1.0 asks for +/-28.6
        degrees off it, clipped to the joint's own travel. MuJoCo then runs
        tau = kp*(target - q) - kv*qdot at the 200 Hz physics rate, ten times
        per control step.

        A ZERO ACTION VECTOR THEREFORE COMMANDS THE STANDING STANCE, which is
        the entire point: standing is the origin of the action space instead
        of a pose the policy must discover and then spend torque holding.

        The four WHEEL entries are unchanged — still a torque fraction. A
        wheel that turns forever has no pose to hold.

        Peak torques are identical (forcerange matches gear), so PD does not
        make the machine stronger, only easier to command. See
        docs/theory/pd-control.md.


OBSERVATION SPACE -- Box(-inf, inf, (169,))
    141 live values, then 28 RESERVED slots held at zero (see __init__):
    3 for a velocity command (roadmap Step 1) and 25 for a terrain height
    scan (Step 3). They are cut now because observation width is the one
    change that orphans every checkpoint, and both features are already
    planned. The live 141 are:
    [  0: 17]  qpos minus world x,y AND MINUS THE FOUR WHEEL ANGLES.
               Trunk z (1), trunk orientation quaternion (4), and the 12
               bounded joint angles (abduction, hip, knee per leg).
    [ 17: 39]  qvel, complete — 6 for the free joint plus all 16 joint
               velocities, wheels included.
    [ 39:141]  cfrc_ext, external contact force/torque (6) for each of the 17
               non-world bodies. This is how the policy feels the ground.

    Dropping x,y is the standard trick and needs no defence: walking looks
    the same everywhere on the plane, so absolute position is an invitation
    to overfit to *where* instead of *how*.

    DROPPING THE WHEEL ANGLES IS THE INTERESTING ONE, and it is the single
    change a wheeled morphology forces on the observation design. Every other
    joint in this repo lives inside a range, so its angle is a bounded,
    stationary feature. A wheel angle is an unbounded integrator: drive at
    30 rad/s for a 1000-step episode and it reaches ~1500 rad, and it is
    still climbing. Feed that to an MLP and

      * the input distribution shifts monotonically for the whole episode,
        so the network sees values in training it will never see again;
      * two physically identical states — same pose, same speed, same ground —
        get wildly different observations depending only on how long the
        episode has run, which is exactly the aliasing the x,y exclusion is
        there to prevent, in a coordinate nobody thinks to check;
      * the replay buffer ends up storing a de-facto episode CLOCK, and SAC
        will happily use it.

    The fix is to notice that the angle carries no information anyway: a
    wheel is rotationally symmetric, so its absolute angle cannot affect the
    dynamics. Only its VELOCITY can, and that is kept in full. (The other
    standard option is to feed sin/cos of the angle, which stays bounded and
    stationary — correct for a *spoked* wheel whose orientation matters, and
    pointless here, where the geometry really is a cylinder.)


REWARD (Ant-v5's terms, ctrl weight retuned for 16 motors)
    reward = forward_velocity              # dx/dt of the trunk, m/s
           + 1.0 * healthy                 # alive bonus, paid every step
           - 0.01 * ||action||^2           # control cost  (see __init__)
           - 5e-4 * ||clip(cfrc,-1,1)||^2  # contact cost

    The control weight is 0.01, NOT the 0.05 the reasoning below arrives at.
    0.05 defended against the suicide exploit but created the opposite trap on
    rough ground, where a slow quadruped's forward term shrinks while its
    torque bill does not — a zero-action policy beat the trained one 960 to 72
    on the 150k run. The full derivation of both bounds is in __init__.

    ON THE PD MODELS THIS TERM MEANS SOMETHING ELSE. The action is an offset
    from the standing stance, not a torque, so ||action||^2 penalizes moving
    the legs AWAY FROM STANDING rather than penalizing effort. Same name,
    different quantity. It may act as an unintended crouch-and-freeze prior,
    and it is flagged as an open question in
    research/episodes/002-pd-position-targets.md rather than silently retuned.

    The 0.05 is inherited reasoning, not a fresh guess. Spyder-v0's postmortem
    (see envs/spyder.py) established that this family of robot can reach
    any credible jump ceiling, so termination can never be made physically
    unreachable, and the only exploit-agnostic defence is to keep being alive
    net-positive for EVERY policy including a flailing one — the Hopper/Walker
    mechanism. Worst case a policy saturates every motor, and the cost is
    w * nu * 1.0. Spyder ran w=0.1 over 12 motors, i.e. 1.2 against a 1.0
    alive bonus: fine in practice because SAC's max-entropy actions sit well
    below saturation, but formally already over the line. Sixteen motors would
    make it 1.6, so w drops to 0.05 and the worst case is 0.80 < 1.00. The
    ordering driving > standing > dying now holds by arithmetic rather than
    by luck, from step one.


PREDICTED FAILURE MODES (written BEFORE the first training run, on purpose)
    The spider's two reward hacks were both found the expensive way, after a
    100K-step run had already been spent. Writing the suspects down first
    costs nothing and makes the postmortem honest either way.

    1. THE SKATEBOARD. Wheels make forward velocity nearly free: four wheels
       at full torque give 8.3 m/s^2 for a torque cost of 4 * 0.05 = 0.2/step,
       against a forward reward that grows without bound. The cheapest policy
       is therefore to freeze all twelve leg joints in the spawn stance and
       spin the wheels — a skateboard, not a dog. On flat ground this is not
       even wrong; it is what a wheel-legged robot SHOULD do, and Hound-v0
       will probably look like that. It is only a failure on Hound-Desert-v0,
       where a dune the wheels cannot climb is the thing that has to make
       legs worth using. That is the whole reason the desert is the target
       and the plane is the sanity check: the terrain IS the shaping term,
       which is what ROADMAP Step 3 claims a curriculum is for.
    2. THE REACTION-WHEEL CHEAT. Four spinning masses on the ends of the legs
       are four reaction wheels. Angular momentum is conserved, so a policy
       can spin them up in the air to torque the trunk and keep the upright
       termination happy without ever using a leg. Watch for wheel speeds
       that oscillate hard while the machine is airborne.
    3. TRACTION THRASH. gear_wheel sits at 94% of the traction limit, so the
       margin between drive and wheelspin is 6%. Policies that discover
       bang-bang wheel torque get slip, and slip is stochastic, which SAC's
       critic will smear. If the learning curve is noisy in a way the spider's
       was not, suspect this before suspecting the hyperparameters.

    None of these have shaping wrappers yet, deliberately. Ship the baseline,
    watch what it actually does, then shape — the order that produced
    FootContactRewardWrapper.


TERMINATION
    Trunk height above the ground under it leaves [0.18, 1.20], the trunk
    tilts past ~72 degrees (up-vector's world-z below 0.30), or any state
    value goes non-finite. Truncation at 1000 steps is set by the
    registration in envs/__init__.py, not here.

    The floor of 0.18 m is a belly check, not a NaN guard: the trunk box is
    0.114 m deep, so its underside reaches the ground at a trunk z of 0.057,
    and the machine has visibly given up well before that. It stands at
    0.363, so 0.18 is roughly "half-collapsed".


TERRAIN (Hound-Desert-v0)
    Same class, same spaces, only the world XML differs — so a flat-world
    checkpoint loads on the desert unchanged, exactly as Spyder-v0's does.
    Two things are terrain-aware: the healthy band measures height above the
    ground beneath the trunk (via terrain/field.py) rather than world z, and
    reset re-bases the spawn on the measured ground under the origin.

    The policy is BLIND: no height samples in the observation. It feels the
    ground only through contacts and posture, like the blind-quadruped line
    of work. Terrain vision would change the obs space and orphan the
    flat-world checkpoint — a deliberate v-next step, not an oversight.

    Note robots/hound/build.py's KNOWN LIMITATION: passive creep of ~5 cm/s backwards
    on the heightfield, an artifact of terrain cells being the same size as
    the wheels. A driving policy dominates it; a standing one must counter it.
"""
from __future__ import annotations


import numpy as np
from gymnasium import utils
from gymnasium.envs.mujoco import MujocoEnv
from gymnasium.spaces import Box

from bestiary import paths
from bestiary.robots.hound.build import SPEC
from bestiary.terrain import HeightField, ground_height_at

HOUND_XML = str(paths.HOUND_XML)

LEGS = ("FL", "FR", "RL", "RR")

DEFAULT_CAMERA_CONFIG = {
    # Tracking camera pinned to the trunk (body 1; body 0 is the world), so
    # eval videos follow the dog instead of filming it driving off-frame.
    "type": 1,  # mjCAMERA_TRACKING
    "trackbodyid": 1,
    "distance": 2.6,
    "elevation": -12.0,
}


class HoundEnv(MujocoEnv, utils.EzPickle):
    # dt = timestep (0.005) * frame_skip (10) = 0.05 s -> the policy acts at
    # 20 Hz, the same rate as every other env here, while physics integrates
    # at 200 Hz. The spider gets away with 100 Hz; this machine does not,
    # because its fastest state is a lightly-damped wheel that passes
    # 40 rad/s. render_fps must match 1/dt.
    metadata = {
        "render_modes": ["human", "rgb_array", "depth_array"],
        "render_fps": 20,
    }

    def __init__(
        self,
        xml_file: str = HOUND_XML,
        frame_skip: int = 10,
        forward_reward_weight: float = 1.0,
        # 0.01. This has now been sized against BOTH failure modes, because
        # the first attempt only defended against one of them.
        #
        # Attempt one was 0.05: half the spider's 0.1, chosen so a saturated
        # policy's torque bill (0.05 x 16 = 0.80) stays under the alive bonus
        # (1.00) and no reachable termination can out-earn living. That closes
        # the SUICIDE exploit and it is still true at 0.01.
        #
        # What it missed is the opposite trap, the one CORE_PLAN.md documents
        # from runs/spyder_desert_v0: on rough ground a quadruped is SLOW, so
        # the forward term shrinks while the torque bill does not. Measured on
        # the 150k run, per step:
        #
        #     forward  +0.20     (0.29 m/s is all it could manage)
        #     costs    -0.45
        #     -> moving nets +0.75/step, standing still nets +0.96/step
        #
        # Standing pays exactly zero control cost (a = 0 -> sum(a^2) = 0), so
        # the reward was quietly instructing the machine to stop, and a
        # zero-action policy beat the trained one 960 to 72. At 0.01 the same
        # gait pays ~0.09/step and nets ~+1.11, so moving wins — and the
        # saturation bound becomes 0.16, comfortably under 1.00.
        #
        # Note what did NOT change: standing's score is untouched. Walking is
        # made affordable rather than standing made painful, which is the
        # distinction CORE_PLAN.md draws and the reason this stays a
        # one-number fix instead of a new reward term.
        ctrl_cost_weight: float = 0.01,
        contact_cost_weight: float = 5e-4,
        healthy_reward: float = 1.0,
        terminate_when_unhealthy: bool = True,
        healthy_z_range: tuple[float, float] = (0.18, 1.20),
        # Minimum world-z of the trunk's up axis. 1.0 = level, 0.0 = on its
        # side. 0.30 terminates past ~72 degrees, far beyond anything a gait
        # needs but well before the machine goes over. The spider needs this
        # rule for the same reason (its v2 postmortem: nothing else in the
        # reward mentions orientation, so SAC found a cartwheel), and it is
        # only safe BECAUSE being alive is net-positive — with that true,
        # terminating on a flip is pure lost income and the optimizer avoids
        # tipping instead of seeking it.
        healthy_up_threshold: float = 0.30,
        contact_force_range: tuple[float, float] = (-1.0, 1.0),
        # 0.05, half the spider's 0.1. Measured, not copied: sweeping the
        # scale over 20 seeds on both worlds, 0.05 settles every seed with
        # only the wheels touching the ground, while 0.08 puts 3/20 on their
        # bellies and 0.10 puts 9/20 there. A reset that starts the episode
        # already fallen teaches nothing.
        reset_noise_scale: float = 0.05,
        # Spawn the wheels this far ABOVE the measured ground. On the desert
        # a reset that lands even slightly inside the heightfield gets a
        # burst of contacts against the vertical walls of the terrain cells,
        # whose normals point sideways; 5 mm of clearance took noisy resets
        # from 2/15 fallen to 0/15. The machine drops onto its springs in
        # about 30 ms, well inside the first control step.
        spawn_clearance: float = 0.005,
        **kwargs,
    ):
        utils.EzPickle.__init__(
            self,
            xml_file,
            frame_skip,
            forward_reward_weight,
            ctrl_cost_weight,
            contact_cost_weight,
            healthy_reward,
            terminate_when_unhealthy,
            healthy_z_range,
            healthy_up_threshold,
            contact_force_range,
            reset_noise_scale,
            spawn_clearance,
            **kwargs,
        )
        self._forward_reward_weight = forward_reward_weight
        self._ctrl_cost_weight = ctrl_cost_weight
        self._contact_cost_weight = contact_cost_weight
        self._healthy_reward = healthy_reward
        self._terminate_when_unhealthy = terminate_when_unhealthy
        self._healthy_z_range = healthy_z_range
        self._healthy_up_threshold = healthy_up_threshold
        self._contact_force_range = contact_force_range
        self._reset_noise_scale = reset_noise_scale
        self._spawn_clearance = spawn_clearance

        MujocoEnv.__init__(
            self,
            xml_file,
            frame_skip,
            observation_space=None,  # set below, once model sizes are known
            default_camera_config=DEFAULT_CAMERA_CONFIG,
            **kwargs,
        )

        # Which qpos slots hold wheel angles. Resolved by NAME, never by
        # index: the whole point of robots/hound/build.py is that the morphology is
        # editable, and a hardcoded slot would silently start reading a knee
        # the first time a link is added.
        self._wheel_qpos_adr = np.array(
            [self.model.jnt_qposadr[self.model.joint(f"{leg}_wheel").id]
             for leg in LEGS],
            dtype=int,
        )
        self._wheel_dof_adr = np.array(
            [self.model.jnt_dofadr[self.model.joint(f"{leg}_wheel").id]
             for leg in LEGS],
            dtype=int,
        )
        if len(self._wheel_qpos_adr) != 4:
            raise RuntimeError("expected exactly 4 wheel joints")

        # The qpos indices the observation KEEPS: everything except world x,y
        # and the four unbounded wheel angles.
        self._obs_qpos_idx = np.array(
            [i for i in range(2, self.model.nq)
             if i not in set(self._wheel_qpos_adr.tolist())],
            dtype=int,
        )

        # RESERVED SLOTS — always zero in v0, and deliberately here anyway.
        #
        # CORE_PLAN.md's step 2 calls the observation list the one truly
        # one-way lock in this project: change its width later and every
        # checkpoint is not degraded but INCOMPATIBLE. Both of the features
        # already on the roadmap widen it — command-conditioned locomotion
        # (Step 1) needs a command vector, terrain-aware climbing (Step 3)
        # needs height samples — so the slots are cut now, filled with zeros,
        # and the run that starts today survives both.
        #
        # Zeros cost one extra input row in the first layer and nothing at
        # all in the dynamics. A from-scratch redo costs hours. This is the
        # cheapest insurance available and it is only available once.
        self._n_command = 3      # [vx, vy, yaw_rate] target — Step 1
        self._n_height = 25      # 5x5 height scan around the trunk — Step 3
        self._reserved = np.zeros(self._n_command + self._n_height)

        # Size the observation from the loaded model rather than hardcoding
        # it, so an XML edit cannot silently desync the env from the robot.
        obs_size = (
            len(self._obs_qpos_idx) + self.model.nv + (self.model.nbody - 1) * 6
            + self._reserved.size
        )
        self.observation_space = Box(
            low=-np.inf, high=np.inf, shape=(obs_size,), dtype=np.float64
        )

        # The standing stance ships in the model as keyframe 0 (robots/hound/build.py
        # writes it), so the pose the env spawns and the pose the springs are
        # preloaded against are read from the same place and cannot drift.
        if self.model.nkey < 1:
            raise RuntimeError(
                f"{xml_file} has no <keyframe>; regenerate it with robots/hound/build.py"
            )
        self.init_qpos = self.model.key_qpos[0].copy()
        self.init_qvel = np.zeros(self.model.nv)

        # --- Action -> ctrl mapping ------------------------------------------
        # Read off the MODEL rather than passed in, so the env cannot disagree
        # with the XML it just loaded. A <position> actuator has an affine
        # bias (tau = kp*(target - q) - kv*qdot); a <motor> has none.
        import mujoco  # local: keeps module import cheap for non-sim callers

        is_position = (
            self.model.actuator_biastype == mujoco.mjtBias.mjBIAS_AFFINE
        )
        self.control_mode = "pd" if is_position.any() else "torque"

        # ctrl = center + action * scale, with action in [-1, 1] either way.
        #
        #   <motor>     center 0, scale 1        -> ctrl IS the torque fraction
        #   <position>  center = stance angle,   -> ctrl is a TARGET ANGLE, and
        #               scale  = action_scale       a zero action commands the
        #                                           stance exactly
        #
        # The second line is the entire point of PD targets: "stand still" is
        # the origin of the action space instead of a pose the policy has to
        # discover and then actively hold.
        self._ctrl_center = np.zeros(self.model.nu)
        self._ctrl_scale = np.ones(self.model.nu)
        for i in range(self.model.nu):
            if not is_position[i]:
                continue
            jnt = self.model.actuator_trnid[i, 0]
            self._ctrl_center[i] = self.model.key_qpos[0][self.model.jnt_qposadr[jnt]]
            self._ctrl_scale[i] = SPEC.action_scale

        # MujocoEnv derives action_space from actuator_ctrlrange, which on the
        # PD model is joint travel in RADIANS. The policy's action is
        # normalized to [-1, 1] in both models — action_to_ctrl is what turns
        # it into ctrl — so the space is restated here. Without this, the two
        # models would present different action spaces for the same policy.
        self.action_space = Box(
            low=-1.0, high=1.0, shape=(self.model.nu,), dtype=np.float32
        )

        # Terrain: re-base the spawn height on the measured ground under the
        # origin, so regenerating the heightfield can never break resets.
        self._hfield = HeightField.from_model(self.model)
        self.init_qpos[2] += (
            ground_height_at(self._hfield, 0.0, 0.0) + self._spawn_clearance
        )

    # --- Reward pieces -------------------------------------------------------

    @property
    def trunk_upright(self) -> float:
        # xmat is the trunk's 3x3 rotation matrix (row-major); element [2,2]
        # is the world-z component of the body's local +z axis — a direct
        # "how level am I" scalar with no quaternion math needed.
        return float(self.data.body("trunk").xmat[8])

    @property
    def height_above_ground(self) -> float:
        pos = self.data.body("trunk").xpos
        return float(pos[2]) - ground_height_at(
            self._hfield, float(pos[0]), float(pos[1])
        )

    @property
    def wheel_speeds(self) -> np.ndarray:
        """Angular velocity of each wheel, rad/s, in LEGS order."""
        return self.data.qvel[self._wheel_dof_adr].copy()

    @property
    def is_healthy(self) -> bool:
        state = self.state_vector()
        min_z, max_z = self._healthy_z_range
        return bool(
            np.isfinite(state).all()
            and min_z <= self.height_above_ground <= max_z
            and self.trunk_upright >= self._healthy_up_threshold
        )

    def control_cost(self, action: np.ndarray) -> float:
        return self._ctrl_cost_weight * float(np.sum(np.square(action)))

    @property
    def contact_cost(self) -> float:
        # cfrc_ext spikes to thousands of newtons on hard impacts; clipping to
        # [-1, 1] before squaring bounds the penalty so one bad landing cannot
        # dominate an episode's return.
        clipped = np.clip(self.data.cfrc_ext, *self._contact_force_range)
        return self._contact_cost_weight * float(np.sum(np.square(clipped)))

    # --- Gym API --------------------------------------------------------------

    def action_to_ctrl(self, action: np.ndarray) -> np.ndarray:
        """Map the policy's [-1, 1] action onto this model's ctrl vector.

        Identity for the torque model. For the PD model, a zero action
        commands the standing stance, and +/-1 commands SPEC.action_scale
        radians either side of it. Clipped to each actuator's ctrlrange so a
        target outside the joint's travel can never be requested.
        """
        ctrl = self._ctrl_center + np.asarray(action) * self._ctrl_scale
        lo, hi = self.model.actuator_ctrlrange.T
        return np.clip(ctrl, lo, hi)

    def step(self, action: np.ndarray):
        xy_before = self.data.body("trunk").xpos[:2].copy()
        self.do_simulation(self.action_to_ctrl(action), self.frame_skip)
        xy_after = self.data.body("trunk").xpos[:2].copy()

        x_velocity, y_velocity = (xy_after - xy_before) / self.dt

        forward_reward = self._forward_reward_weight * x_velocity
        healthy_reward = self._healthy_reward if self.is_healthy else 0.0
        ctrl_cost = self.control_cost(action)
        contact_cost = self.contact_cost

        reward = forward_reward + healthy_reward - ctrl_cost - contact_cost
        terminated = self._terminate_when_unhealthy and not self.is_healthy

        observation = self._get_obs()
        wheels = self.wheel_speeds
        info = {
            "reward_forward": forward_reward,
            "reward_survive": healthy_reward,
            "reward_ctrl": -ctrl_cost,
            "reward_contact": -contact_cost,
            "x_position": float(self.data.body("trunk").xpos[0]),
            "y_position": float(self.data.body("trunk").xpos[1]),
            "x_velocity": float(x_velocity),
            "y_velocity": float(y_velocity),
            "trunk_upright": self.trunk_upright,
            "height_above_ground": self.height_above_ground,
            # Wheel diagnostics. These are the numbers that separate the
            # predicted failure modes from a real gait: rolling_fraction near
            # 1.0 with dead legs is the skateboard, and wheel_speed_std high
            # while airborne is the reaction-wheel cheat.
            "wheel_speed_mean": float(np.mean(wheels)),
            "wheel_speed_std": float(np.std(wheels)),
            # Body speed as a fraction of wheel SURFACE speed (omega * r).
            #   ~1.0  pure rolling — the contact patch is not sliding
            #   ~0.0  wheelspin — wheels turning, machine going nowhere
            #    >1   the legs are doing it; the body is outrunning its wheels
            # Guarded on the wheel term, not the body term: at a standstill
            # the ratio is meaningless either way, but dividing by the body
            # speed made it explode to 9.07 during ordinary wheelspin.
            "rolling_fraction": float(
                x_velocity / (np.mean(wheels) * 0.085)
            ) if abs(np.mean(wheels)) * 0.085 > 0.2 else 0.0,
        }
        if self.render_mode == "human":
            self.render()
        return observation, reward, terminated, False, info

    def _get_obs(self) -> np.ndarray:
        position = self.data.qpos[self._obs_qpos_idx]
        velocity = self.data.qvel.flatten()
        contact_force = self.data.cfrc_ext[1:].flatten()  # [1:] skips world
        # _reserved is all zeros in v0 — see __init__. It goes LAST so the
        # first 141 entries stay exactly what the docstring describes, and a
        # future version can fill it without moving anything else.
        return np.concatenate((position, velocity, contact_force, self._reserved))

    def reset_model(self) -> np.ndarray:
        """Spawn in the authored stance, lightly perturbed.

        Two departures from the spider's reset, both deliberate:

        * The trunk QUATERNION is left alone. Adding uniform noise to four
          quaternion components and renormalizing is not a small rotation —
          at scale 0.05 it is several degrees of arbitrary tilt, and on the
          heightfield that tilt is what drives a wheel into the terrain and
          triggers the sideways-normal contacts described in robots/hound/build.py.
          Orientation still varies across an episode; it just is not
          scrambled at t=0.
        * The WHEEL ANGLES are left at zero. They are unobserved and
          dynamically irrelevant (a cylinder is rotationally symmetric), so
          perturbing them randomizes nothing and only makes logs harder to
          read.

        Everything that does matter — the twelve leg angles, and every
        velocity — is perturbed as usual.
        """
        scale = self._reset_noise_scale
        qpos = self.init_qpos.copy()
        leg_idx = [i for i in range(7, self.model.nq)
                   if i not in set(self._wheel_qpos_adr.tolist())]
        qpos[leg_idx] += self.np_random.uniform(-scale, scale, size=len(leg_idx))
        qvel = self.init_qvel + scale * self.np_random.standard_normal(self.model.nv)
        self.set_state(qpos, qvel)
        return self._get_obs()
