"""Turn spec.py into CAD parameters, STLs, and a machine-readable robot description.

    python -m bestiary.robots.whelp.export              # params + robot.json (no CAD needed)
    python -m bestiary.robots.whelp.export --stl        # ...and render every STL
    python -m bestiary.robots.whelp.export --stl --check-mass   # ...and verify the mass model

WHAT "SINGLE SOURCE OF TRUTH" MEANS HERE, AND WHY IT IS NOT build.scad
----------------------------------------------------------------------
The brief asked for build.scad to be the single source. It very nearly is, and
the difference is deliberate, so it is written down rather than assumed.

    spec.py          THE NUMBERS.    Every dimension, with provenance.
    geometry.py      THE DERIVATION. Stance solve, joint origins, axes.
    scad/*.scad      THE GEOMETRY.   How those numbers become solids.

`params_gen.scad` and `derived_gen.scad` are GENERATED from the first two by
this file and must never be hand-edited; check.py fails if regenerating them
changes anything. build.scad includes them, so the CAD has exactly one source
for every number and the assembly preview is posed at the same solved stance
angles the URDF carries.

The reason not to put the numbers in build.scad is that OpenSCAD cannot do the
work. The stance knee angle is the solution of an inverse-kinematics problem;
the design stress is a product of three measured knockdowns; the mass budget is
a parallel-axis sum over sixty primitives. Those belong in Python, and once they
are in Python, having a SECOND authoritative copy of the lengths in .scad is
precisely the duplication the rule exists to prevent.

And no STL is ever hand-edited, which was the actual point.

NOTHING EXCEPT STL GENERATION REQUIRES OpenSCAD
-----------------------------------------------
robot.json, the URDF, the torque report and every check run on plain Python.
That is not a convenience: a pipeline where regenerating the robot description
needs a CAD binary is a pipeline that breaks on the training machine, in CI, and
on anybody else's laptop. OpenSCAD is needed to produce printable geometry and
for nothing else.

THE CROSS-CHECK THAT MAKES THE MASS MODEL TRUSTWORTHY
-----------------------------------------------------
massmodel.py is a second, independent implementation of the geometry in
scad/parts/. Two implementations of one thing drift. So when OpenSCAD IS present,
`--check-mass` renders each part, measures the real mesh with stl.py, and asserts
the analytic volume agrees within massmodel.MASS_MODEL_TOL -- and separately that
every mesh is watertight, since the volume of an open mesh is not a volume, it is
just a number that a divergence-theorem sum happens to return.
"""
from __future__ import annotations

import json
import math
import shutil
import subprocess
import sys
from pathlib import Path

from bestiary import paths
from bestiary.robots.whelp import geometry as geo
from bestiary.robots.whelp import stl
from bestiary.robots.whelp.massmodel import MASS_MODEL_TOL, PRINTED_PARTS, link_bodies
from bestiary.robots.whelp.spec import SPEC, Spec

SCAD_DIR = Path(__file__).resolve().parent / "scad"
OUT_DIR = paths.ASSETS / "whelp"
STL_DIR = OUT_DIR / "stl"
ROBOT_JSON = OUT_DIR / "robot.json"

PARAMS_GEN = SCAD_DIR / "lib" / "params_gen.scad"
DERIVED_GEN = SCAD_DIR / "lib" / "derived_gen.scad"

_BANNER = (
    "// GENERATED by `python -m bestiary.robots.whelp.export`. DO NOT EDIT.\n"
    "//\n"
    "// Every number here comes from spec.py, which carries its provenance, or from\n"
    "// geometry.py, which derives it. check.py fails if regenerating this file changes\n"
    "// it, so a hand edit here is not merely discouraged -- it is caught.\n"
    "//\n"
    "// To change a dimension: edit spec.py, re-run export, commit both.\n"
    "\n"
)


def _scad_value(v: object) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return f"{v:.6f}".rstrip("0").rstrip(".") or "0"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, (tuple, list)):
        return "[" + ", ".join(_scad_value(x) for x in v) + "]"
    raise TypeError(f"cannot express {v!r} ({type(v).__name__}) in OpenSCAD")


#: Spec attribute -> the constant name build.scad sees. Only what the CAD needs
#: is exported: a parameter file that mirrors all of Spec would tempt somebody to
#: put geometry logic in .scad that belongs in Python.
SCAD_PARAMS: dict[str, str] = {
    "trunk_len_mm": "TRUNK_L", "trunk_width_mm": "TRUNK_W", "trunk_height_mm": "TRUNK_H",
    "trunk_wall_mm": "TRUNK_WALL", "trunk_split_lap_mm": "TRUNK_LAP",
    "abduct_x_mm": "ABDUCT_X", "abduct_y_mm": "ABDUCT_Y",
    "abduct_to_hip_mm": "ABDUCT_TO_HIP",
    "abduct_to_hip_drop_mm": "ABDUCT_TO_HIP_DROP",
    "thigh_len_mm": "THIGH_L", "calf_len_mm": "CALF_L",
    "wheel_radius_mm": "WHEEL_R", "wheel_width_mm": "WHEEL_W",
    "calf_to_wheel_plane_mm": "CALF_TO_WHEEL_PLANE",
    "thigh_section_fore_aft_mm": "THIGH_D", "thigh_section_lateral_mm": "THIGH_WID",
    "thigh_wall_mm": "THIGH_WALL",
    "calf_section_fore_aft_mm": "CALF_D", "calf_section_lateral_mm": "CALF_WID",
    "calf_wall_mm": "CALF_WALL", "fillet_r_mm": "FILLET_R",
    "servo_body_l_mm": "SERVO_BODY_L", "servo_body_w_mm": "SERVO_BODY_W",
    "servo_body_h_mm": "SERVO_BODY_H",
    "horn_bolt_circle_mm": "SERVO_HORN_BOLT_CIRCLE_D", "horn_bolt_count": "SERVO_HORN_BOLT_COUNT",
    "horn_bolt_dia_mm": "SERVO_HORN_BOLT_D", "horn_disc_d_mm": "SERVO_HORN_D",
    "horn_thick_mm": "SERVO_HORN_THICK", "horn_boss_thick_mm": "HORN_BOSS_THICK",
    "horn_face_to_body_mm": "SERVO_HORN_FACE_TO_BODY",
    "horn_hub_clear_d_mm": "SERVO_HORN_HUB_CLEAR_D",
    "horn_hub_clear_h_mm": "SERVO_HORN_HUB_CLEAR_H",
    "servo_mount_hole_dx_mm": "SERVO_MOUNT_HOLE_DX",
    "servo_mount_hole_dy_mm": "SERVO_MOUNT_HOLE_DY",
    "servo_ear_span_l_mm": "SERVO_EAR_SPAN_L", "servo_ear_thick_mm": "SERVO_EAR_THICK",
    "servo_ear_z_from_body_mid_mm": "SERVO_EAR_Z_FROM_BODY_MID",
    "servo_has_rear_boss": "SERVO_HAS_REAR_BOSS",
    "servo_rear_boss_d_mm": "SERVO_REAR_BOSS_D", "servo_rear_boss_h_mm": "SERVO_REAR_BOSS_H",
    "servo_output_boss_d_mm": "SERVO_OUTPUT_BOSS_D",
    "servo_cable_d_mm": "SERVO_CABLE_D", "servo_cable_inset_mm": "SERVO_CABLE_INSET",
    "servo_cable_stub_mm": "SERVO_CABLE_STUB",
    "insert_bore_mm": "INSERT_BORE", "insert_od_mm": "INSERT_OD", "insert_len_mm": "INSERT_L",
    "insert_wall_mm": "INSERT_WALL",
    "m3_clear_mm": "M3_CLEAR", "m3_head_d_mm": "M3_HEAD_D", "m3_head_h_mm": "M3_HEAD_H",
    "m3_nut_af_mm": "M3_NUT_AF", "m3_nut_thick_mm": "M3_NUT_T",
    "idler_bearing_id_mm": "IDLER_BEARING_ID", "idler_bearing_od_mm": "IDLER_BEARING_OD",
    "idler_bearing_w_mm": "IDLER_BEARING_W", "idler_bearing_shelf_mm": "IDLER_BEARING_SHELF",
    "bearing_press_fit_mm": "BEARING_PRESS_FIT",
    "tire_thickness_mm": "TIRE_T", "fuse_thick_mm": "FUSE_T",
    "fuse_shear_area_mm2": "FUSE_SHEAR_AREA", "fuse_enable": "FUSE_ENABLE",
    "bed_x_mm": "BED_X", "bed_y_mm": "BED_Y", "bed_z_mm": "BED_Z",
    "nozzle_mm": "NOZZLE", "layer_mm": "LAYER", "scad_fn": "FN",
}

#: Screw clearance for the servo's own case screws, and for the horn screws.
#: Derived here rather than stored, because they are "the nominal thread plus a
#: printing allowance" and storing them would let the two drift apart.
_DERIVED_SCAD_EXTRA = {
    "SERVO_MOUNT_SCREW_CLEAR_D": lambda s: s.servo_mount_screw_mm + 0.4,
    "SERVO_MOUNT_SCREW_HEAD_D": lambda s: s.servo_mount_screw_mm * 2.0,
    "SERVO_MOUNT_SCREW_HEAD_H": lambda s: s.servo_mount_screw_mm * 1.0,
    "SERVO_HORN_BOLT_CLEAR_D": lambda s: s.horn_bolt_dia_mm + 0.35,
}


def render_params_scad(spec: Spec = SPEC) -> str:
    """Format the parameter file. PURE -- writes nothing.

    Split from write_params_scad because check.py's freshness assertion compared
    the file on disk against the WRITER's return value, and the writer had
    already overwritten the file by the time the comparison ran. The check was
    therefore correct exactly once and self-healing forever after: a hand edit
    was silently reverted rather than reported, and -- worse -- a check run under
    a broken module wrote corrupted content into the tracked source tree and the
    next clean run erased the evidence.

    A verifier must not be able to change what it verifies. Rendering and writing
    are now different functions, and check.py only calls this one.
    """
    lines = [_BANNER, f"// {len(SCAD_PARAMS) + len(_DERIVED_SCAD_EXTRA)} constants,",
             f"// spec = {spec.name}, servo = {spec.servo_variant}, "
             f"material = {spec.material}\n"]
    for attr, const in SCAD_PARAMS.items():
        lines.append(f"{const} = {_scad_value(getattr(spec, attr))};")
    lines.append("\n// Derived clearances (nominal thread + printing allowance).")
    for const, fn in _DERIVED_SCAD_EXTRA.items():
        lines.append(f"{const} = {_scad_value(fn(spec))};")
    return "\n".join(lines) + "\n"


def write_params_scad(spec: Spec = SPEC) -> str:
    text = render_params_scad(spec)
    PARAMS_GEN.parent.mkdir(parents=True, exist_ok=True)
    PARAMS_GEN.write_text(text, encoding="utf-8")
    return text


def render_derived_scad(spec: Spec = SPEC) -> str:
    """The SOLVED stance and the assembly frames, so the preview matches the URDF.

    This is the file that makes the CAD and the simulation the same robot. The
    knee angle here is the output of geometry.solve_stance_knee, the identical
    call urdf_gen.py makes, so a render and an Isaac Lab spawn cannot disagree
    about what "standing" means.
    """
    knee = geo.solve_stance_knee(spec)
    lines = [
        _BANNER,
        "// The SOLVED standing stance. Not typed -- geometry.solve_stance_knee()\n"
        "// puts the wheel axle directly under the hip pivot, which makes the hip's\n"
        "// static holding torque exactly zero. The URDF is generated from this same\n"
        "// call, so the assembly preview and the simulation cannot drift apart.\n",
        f"STANCE_ABDUCT = {_scad_value(spec.stance_abduct_rad)};   // rad",
        f"STANCE_HIP    = {_scad_value(spec.stance_hip_rad)};",
        f"STANCE_KNEE   = {_scad_value(knee)};",
        f"STANCE_ABDUCT_DEG = {_scad_value(math.degrees(spec.stance_abduct_rad))};",
        f"STANCE_HIP_DEG    = {_scad_value(math.degrees(spec.stance_hip_rad))};",
        f"STANCE_KNEE_DEG   = {_scad_value(math.degrees(knee))};",
        "",
        f"AXLE_DROP     = {_scad_value(geo.axle_drop_mm(spec))};   // hip pivot -> axle, mm",
        f"KNEE_LEVER    = {_scad_value(geo.knee_lever_mm(spec))};",
        f"STAND_HEIGHT  = {_scad_value(geo.stand_height_mm(spec))};",
        f"WHEEL_CENTRE_Y = {_scad_value(spec.wheel_centre_y_mm)};",
        f"LOADED_WHEEL_R = {_scad_value(spec.wheel_radius_mm - spec.tire_static_sag_mm)};",
        "",
        "// Leg placement: [x sign, y sign] per leg, in FL FR RL RR order.",
        "LEG_SIGNS = " + _scad_value([list(geo.SIGNS[leg]) for leg in geo.LEGS]) + ";",
        'LEG_NAMES = ' + _scad_value(list(geo.LEGS)) + ";",
    ]
    return "\n".join(lines) + "\n"


def write_derived_scad(spec: Spec = SPEC) -> str:
    text = render_derived_scad(spec)
    DERIVED_GEN.parent.mkdir(parents=True, exist_ok=True)
    DERIVED_GEN.write_text(text, encoding="utf-8")
    return text


# ── robot.json ───────────────────────────────────────────────────────────────
def robot_dict(spec: Spec = SPEC) -> dict:
    """Everything urdf_gen.py and check.py need, with nothing they have to re-derive."""
    chain = geo.build_chain(spec)
    bodies = link_bodies(spec)
    knee = geo.solve_stance_knee(spec)

    links = []
    for link in chain.links:
        b = bodies[link.name]
        ok, why = b.inertia_is_valid()
        i = b.inertia_kgm2
        links.append({
            "name": link.name,
            "is_root": link.is_root,
            "mass_kg": b.mass_kg,
            "com_m": list(b.com_m),
            "inertia": {"ixx": i[0][0], "ixy": i[0][1], "ixz": i[0][2],
                        "iyy": i[1][1], "iyz": i[1][2], "izz": i[2][2]},
            "inertia_valid": ok,
            "inertia_problem": why,
            "printed_cm3": b.printed_cm3,
            "parts": list(link.parts),
        })

    joints = []
    for j in chain.joints:
        joints.append({
            "name": j.name, "parent": j.parent, "child": j.child,
            "type": "continuous" if j.continuous else "revolute",
            "origin_xyz": list(j.origin_xyz), "origin_rpy": list(j.origin_rpy),
            "axis": list(j.axis),
            "limit_lower": None if j.continuous else j.limit[0],
            "limit_upper": None if j.continuous else j.limit[1],
            "effort_nm": j.effort_nm, "velocity_rad_s": j.velocity_rad_s,
            "damping": j.damping, "friction": j.friction,
            "armature_kgm2": spec.servo_armature_kgm2,
            "stance_rad": j.stance, "leg": j.leg, "kind": j.kind,
        })

    contacts = geo.contact_points(chain, spec)
    xs = [c[0] for c in contacts.values()]
    ys = [c[1] for c in contacts.values()]

    return {
        "name": spec.name,
        "generated_by": "bestiary.robots.whelp.export",
        "units": {"length": "m", "angle": "rad", "mass": "kg", "inertia": "kg m^2"},
        "convention": "+X forward, +Y left, +Z up, right-handed",
        "servo_variant": spec.servo_variant,
        "material": spec.material,
        "root_link": "trunk",
        "links": links,
        "joints": joints,
        "stance": {j.name: j.stance for j in chain.joints},
        "stance_solved_knee_rad": knee,
        "stand_height_m": geo.stand_height_mm(spec) / 1000.0,
        "wheelbase_m": max(xs) - min(xs),
        "track_m": max(ys) - min(ys),
        "total_mass_kg": sum(b.mass_kg for b in bodies.values()),
        "wheel": {
            "radius_m": spec.wheel_radius_mm / 1000.0,
            "loaded_radius_m": (spec.wheel_radius_mm - spec.tire_static_sag_mm) / 1000.0,
            "width_m": spec.wheel_width_mm / 1000.0,
        },
        "actuator_note": (
            "The STS3215 is a closed-loop POSITION servo with an internal integer-gain "
            "PID, a deadband and 1:345 of reduction. It has no torque and no current "
            "mode. Model it as a saturating position-PD with the armature above, not as "
            "an ideal effort source. Wheels must be VELOCITY-driven: a continuous joint "
            "position target breaks past +/-2*pi in PhysX."
        ),
        "envelope": {
            "top_speed_m_s": (spec.wheel_drive_no_load_rad_s
                              * (spec.wheel_radius_mm - spec.tire_static_sag_mm) / 1000.0),
            "leg_joint_rad_s": spec.leg_servo_no_load_rad_s,
            "design_drop_m": spec.design_drop_height_mm / 1000.0,
        },
    }


def write_robot_json(spec: Spec = SPEC) -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ROBOT_JSON.write_text(json.dumps(robot_dict(spec), indent=2) + "\n", encoding="utf-8")
    return ROBOT_JSON


# ── STL ──────────────────────────────────────────────────────────────────────
def openscad_binary() -> str | None:
    for name in ("openscad", "openscad-nightly", "OpenSCAD"):
        found = shutil.which(name)
        if found:
            return found
    return None


def render_stls(spec: Spec = SPEC, parts: list[str] | None = None) -> dict[str, Path]:
    """Render one STL per printed part. Requires OpenSCAD on PATH."""
    binary = openscad_binary()
    if binary is None:
        raise RuntimeError(
            "OpenSCAD is not on PATH, so STLs cannot be rendered.\n"
            "  Debian/Ubuntu:  sudo apt install openscad\n"
            "  or:             sudo snap install openscad\n"
            "Everything else in this package -- robot.json, the URDF, the torque report,\n"
            "the checks -- runs without it."
        )
    STL_DIR.mkdir(parents=True, exist_ok=True)
    names = parts or sorted(PRINTED_PARTS)
    out: dict[str, Path] = {}
    for name in names:
        target = STL_DIR / f"{name}.stl"
        cmd = [binary, "-o", str(target),
               "-D", f'PART="{name}"', "-D", f"FN={spec.scad_fn}",
               str(SCAD_DIR / "build.scad")]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0 or not target.exists():
            raise RuntimeError(
                f"OpenSCAD failed on part {name!r} (exit {proc.returncode}).\n"
                f"  command: {' '.join(cmd)}\n"
                f"  stderr:  {proc.stderr.strip()[:2000]}"
            )
        out[name] = target
    return out


def check_masses(spec: Spec = SPEC) -> list[str]:
    """Compare the analytic mass model against measured STL volume. Returns problems.

    The whole reason the analytic model is allowed to exist. Without this it is an
    unfalsifiable second implementation of the geometry, and those are always
    wrong eventually.
    """
    from bestiary.robots.whelp.massmodel import _printed

    problems: list[str] = []
    for name in sorted(PRINTED_PARTS):
        path = STL_DIR / f"{name}.stl"
        if not path.exists():
            problems.append(f"{name}: no STL at {path}; run with --stl first")
            continue
        mesh = stl.read(path)
        if not mesh.watertight:
            problems.append(
                f"{name}: mesh is NOT watertight ({mesh.open_edges} open edges, "
                f"{mesh.nonmanifold_edges} non-manifold). Its volume is meaningless, and "
                f"the slicer will disagree with it too -- usually a difference() with a "
                f"coincident face."
            )
            continue
        if mesh.volume_mm3 < 0:
            problems.append(f"{name}: mesh volume is negative; the solid is inside-out")
            continue
        if not mesh.fits(spec.bed_x_mm, spec.bed_y_mm, spec.bed_z_mm):
            sx, sy, sz = mesh.size_mm
            problems.append(
                f"{name}: {sx:.0f} x {sy:.0f} x {sz:.0f} mm does not fit the "
                f"{spec.bed_x_mm:.0f} x {spec.bed_y_mm:.0f} x {spec.bed_z_mm:.0f} mm bed "
                f"in any axis-aligned orientation"
            )
        model_cm3 = _printed(name, spec)[2]
        real_cm3 = mesh.volume_cm3
        if real_cm3 > 1e-6:
            err = abs(model_cm3 - real_cm3) / real_cm3
            if err > MASS_MODEL_TOL:
                problems.append(
                    f"{name}: mass model says {model_cm3:.2f} cm^3, the mesh measures "
                    f"{real_cm3:.2f} cm^3 -- {err:.0%} apart, over the {MASS_MODEL_TOL:.0%} "
                    f"tolerance. Either massmodel.part_{name}() or scad/parts/{name}.scad "
                    f"has drifted from the other."
                )
    return problems


def main(argv: list[str]) -> int:
    spec = SPEC
    write_params_scad(spec)
    write_derived_scad(spec)
    path = write_robot_json(spec)
    r = robot_dict(spec)

    print(f"wrote {PARAMS_GEN.relative_to(Path.cwd()) if PARAMS_GEN.is_relative_to(Path.cwd()) else PARAMS_GEN}")
    print(f"wrote {DERIVED_GEN.name}")
    print(f"wrote {path}")
    print(f"  {len(r['links'])} links, {len(r['joints'])} joints, "
          f"{r['total_mass_kg']:.3f} kg")
    print(f"  wheelbase {r['wheelbase_m'] * 1000:.0f} mm, track {r['track_m'] * 1000:.0f} mm, "
          f"stand height {r['stand_height_m'] * 1000:.0f} mm")

    bad_inertia = [ln["name"] for ln in r["links"] if not ln["inertia_valid"]]
    if bad_inertia:
        print(f"  INVALID INERTIA on: {', '.join(bad_inertia)}")
        return 1

    if "--stl" in argv:
        try:
            out = render_stls(spec)
        except RuntimeError as exc:
            print(f"\n{exc}")
            return 2
        print(f"\nrendered {len(out)} STLs into {STL_DIR}")
        for name, p in sorted(out.items()):
            print("  " + stl.read(p).describe())

    if "--check-mass" in argv:
        problems = check_masses(spec)
        if problems:
            print(f"\nMASS / GEOMETRY CROSS-CHECK FAILED ({len(problems)}):")
            for p in problems:
                print(f"  - {p}")
            return 1
        print("\nmass model agrees with every measured STL, all parts watertight and on the bed")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
