"""Every filesystem path in the project resolves from here.

Modules must never build paths with `Path(__file__).parent.parent` chains.
Those encode how deep a file happens to sit in the tree, so they break the
moment the file moves -- which is exactly what happened during the refactor
that created this module. Import the constant instead.

Nothing here may depend on the current working directory either, since a
session can be started from anywhere. `RUNS` below is absolute for that reason:
`Path("runs")` silently wrote to the wrong place when a script was launched
from anywhere other than the repo root.
"""
from __future__ import annotations

from pathlib import Path

# src/bestiary/paths.py -> src/bestiary -> src -> repo root
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

ASSETS = REPO_ROOT / "assets"      # generated models, meshes, terrain, figures
RUNS = REPO_ROOT / "runs"          # per-run dirs; gitignored, tens of GB
RESEARCH = REPO_ROOT / "research"  # learnings, decisions, episodes, ledger
DOCS = REPO_ROOT / "docs"

LEDGER = RESEARCH / "ledger.jsonl"  # append-only, one row per finished run
RETIRED = RESEARCH / "retired_runs.jsonl"  # append-only, one row per orphaned run

# One row per recorded dead end. This constant did not exist until 2026-07-27,
# and its absence was the whole problem: `anomalies.jsonl` recorded that nothing
# in src/ referenced nulls.jsonl -- no path, no schema, no reader -- so the
# hound re-entered row 2's dead end twice, for ~10.7 GPU-hours, with every guard
# green. A record only a human reads is not a guard, and this loop is designed
# to run without one.
NULLS = RESEARCH / "nulls.jsonl"

# --- Model XMLs -------------------------------------------------------------
# MuJoCo resolves <mesh file="meshes/..."> and <hfield file="terrain/..."> as
# paths RELATIVE TO THE XML'S OWN DIRECTORY. Every model below therefore has
# to sit in ASSETS, next to meshes/ and terrain/. Moving a model XML into its
# robot folder breaks asset resolution at load time with a bare file-not-found
# and no hint about why. The robot folders hold source (build, check, card);
# ASSETS holds generated output. Keep that split.
TERRAIN_DIR = ASSETS / "terrain"
MESH_DIR = ASSETS / "meshes"

# The compiled desert itself, named here rather than rebuilt at each call site.
# `terrain/generate.py` writes it, `terrain/spec.py` hashes it, and
# `terrain/isaac_hf.py` reads it from a *different interpreter* — three places
# that must agree on one filename, which is the case this module exists for.
DESERT_HFIELD = TERRAIN_DIR / "desert_hfield.bin"
DESERT_TEXTURE = TERRAIN_DIR / "desert_texture.png"

# The gentle terrain: same 1024^2 half-extent-40 m format as the desert, a
# fraction of its relief. A NEW asset rather than a regenerated desert, because
# the desert's bytes are hash-pinned into every run that stood on it —
# `terrain/spec.py` and the terrain invariant in CLAUDE.md are the reasons an
# edit in place is not an option. Written by `terrain/gentle.py`.
GENTLE_HFIELD = TERRAIN_DIR / "gentle_hfield.bin"
GENTLE_TEXTURE = TERRAIN_DIR / "gentle_texture.png"

# --- Whelp: the PHYSICAL robot ----------------------------------------------
# Whelp is CAD rather than MJCF, so it does not follow the "model XML sits next
# to meshes/" rule above -- nothing here is loaded by MuJoCo's relative-path
# resolver. It keeps the same source-vs-output split though: the .scad source and
# the generators live in robots/whelp/, and everything generated lands here.
#
# whelp16.urdf references its meshes as "stl/<part>.stl", RELATIVE TO THE URDF,
# so the URDF and the stl/ directory have to stay siblings. Isaac Lab's importer
# resolves them the same way MuJoCo does.
WHELP_DIR = ASSETS / "whelp"
WHELP_STL_DIR = WHELP_DIR / "stl"
WHELP_URDF = WHELP_DIR / "whelp16.urdf"
WHELP_ROBOT_JSON = WHELP_DIR / "robot.json"

HOUND_XML = ASSETS / "hound16.xml"
HOUND_DESERT_XML = ASSETS / "hound16_desert.xml"

# Same robot, same 16 action slots in the same order — the twelve leg joints
# are <position> servos instead of <motor>. Kept as a separate model rather
# than replacing the torque one so the two can be compared head to head in
# research/ledger.jsonl, and so hound_desert_v0's checkpoint still loads.
HOUND_PD_XML = ASSETS / "hound16pd.xml"
HOUND_PD_DESERT_XML = ASSETS / "hound16pd_desert.xml"

# --- Hound in Isaac Lab -----------------------------------------------------
# The USD port of the PD variant, generated by `bestiary.isaac.hound_usd`.
#
# It is a THIRD generated model of the same machine, and it is deliberately not
# a copy of HOUND_PD_XML: the conversion input carries the robot subtree only
# (no floor, no light, no world) and authors the trunk at the origin instead of
# at spec.stand_z. Both deltas are explained where they are produced.
#
# The `.usda` path is nested one level deeper than it looks because Isaac Lab's
# MjcfConverter derives the output layout from the input file's stem and writes
# `<usd_dir>/<stem>/<stem>.usda` alongside a `payloads/` directory. That is the
# importer's structure, not ours; naming it here is what keeps every reader
# (converter, articulation cfg, oracle) pointed at one file.
HOUND_ISAAC_DIR = ASSETS / "hound" / "isaac"
HOUND_ISAAC_MJCF = HOUND_ISAAC_DIR / "hound16pd_isaac.xml"
HOUND_ISAAC_USD = HOUND_ISAAC_DIR / "hound16pd_isaac" / "hound16pd_isaac.usda"
SPYDER_XML = ASSETS / "spyder12.xml"
SPYDER_DESERT_XML = ASSETS / "spyder12_desert.xml"

# --- Spyder in Isaac Lab ----------------------------------------------------
# Same layout contract as the Hound port above: the conversion input is a
# transformed copy of SPYDER_XML (world stripped, torso at the origin), and the
# `.usda` nests one level deeper because MjcfConverter derives its output
# layout from the input stem. Generated by `bestiary.isaac.spyder_usd`.
SPYDER_ISAAC_DIR = ASSETS / "spyder" / "isaac"
SPYDER_ISAAC_MJCF = SPYDER_ISAAC_DIR / "spyder12_isaac.xml"
SPYDER_ISAAC_USD = SPYDER_ISAAC_DIR / "spyder12_isaac" / "spyder12_isaac.usda"
