// GENERATED by `python -m bestiary.robots.whelp.export`. DO NOT EDIT.
//
// Every number here comes from spec.py, which carries its provenance, or from
// geometry.py, which derives it. check.py fails if regenerating this file changes
// it, so a hand edit here is not merely discouraged -- it is caught.
//
// To change a dimension: edit spec.py, re-run export, commit both.


// The SOLVED standing stance. Not typed -- geometry.solve_stance_knee()
// puts the wheel axle directly under the hip pivot, which makes the hip's
// static holding torque exactly zero. The URDF is generated from this same
// call, so the assembly preview and the simulation cannot drift apart.

STANCE_ABDUCT = 0;   // rad
STANCE_HIP    = 0.46;
STANCE_KNEE   = -0.97019;
STANCE_ABDUCT_DEG = 0;
STANCE_HIP_DEG    = 26.356059;
STANCE_KNEE_DEG   = -55.587783;

AXLE_DROP     = 185.830956;   // hip pivot -> axle, mm
KNEE_LEVER    = 48.834292;
STAND_HEIGHT  = 229.430956;
WHEEL_CENTRE_Y = 89;
LOADED_WHEEL_R = 43.6;

// Leg placement: [x sign, y sign] per leg, in FL FR RL RR order.
LEG_SIGNS = [[1, 1], [1, -1], [-1, 1], [-1, -1]];
LEG_NAMES = ["FL", "FR", "RL", "RR"];
