// GENERATED by `python -m bestiary.robots.whelp.export`. DO NOT EDIT.
//
// Every number here comes from spec.py, which carries its provenance, or from
// geometry.py, which derives it. check.py fails if regenerating this file changes
// it, so a hand edit here is not merely discouraged -- it is caught.
//
// To change a dimension: edit spec.py, re-run export, commit both.


// 73 constants,
// spec = whelp16, servo = STS3215-C018, material = PETG

TRUNK_L = 250;
TRUNK_W = 104;
TRUNK_H = 58;
TRUNK_WALL = 2.4;
TRUNK_LAP = 26;
ABDUCT_X = 92;
ABDUCT_Y = 36;
ABDUCT_TO_HIP = 36;
ABDUCT_TO_HIP_DROP = 0;
THIGH_L = 110;
CALF_L = 100;
WHEEL_R = 45;
WHEEL_W = 24;
CALF_TO_WHEEL_PLANE = 17;
THIGH_D = 30;
THIGH_WID = 32;
THIGH_WALL = 3.2;
CALF_D = 26;
CALF_WID = 24;
CALF_WALL = 3.2;
FILLET_R = 3;
SERVO_BODY_L = 45.2;
SERVO_BODY_W = 24.7;
SERVO_BODY_H = 35;
SERVO_HORN_BOLT_CIRCLE_D = 17;
SERVO_HORN_BOLT_COUNT = 4;
SERVO_HORN_BOLT_D = 2;
SERVO_HORN_D = 22;
SERVO_HORN_THICK = 2.5;
HORN_BOSS_THICK = 5;
SERVO_HORN_FACE_TO_BODY = 3.5;
SERVO_HORN_HUB_CLEAR_D = 9;
SERVO_HORN_HUB_CLEAR_H = 4;
SERVO_MOUNT_HOLE_DX = 38;
SERVO_MOUNT_HOLE_DY = 18;
SERVO_EAR_SPAN_L = 54;
SERVO_EAR_THICK = 2.5;
SERVO_EAR_Z_FROM_BODY_MID = 10;
SERVO_HAS_REAR_BOSS = true;
SERVO_REAR_BOSS_D = 6;
SERVO_REAR_BOSS_H = 2;
SERVO_OUTPUT_BOSS_D = 12;
SERVO_CABLE_D = 5;
SERVO_CABLE_INSET = 6;
SERVO_CABLE_STUB = 18;
INSERT_BORE = 4.2;
INSERT_OD = 4.6;
INSERT_L = 5.7;
INSERT_WALL = 1.8;
M3_CLEAR = 3.4;
M3_HEAD_D = 5.5;
M3_HEAD_H = 3;
M3_NUT_AF = 5.5;
M3_NUT_T = 2.4;
IDLER_BEARING_ID = 3;
IDLER_BEARING_OD = 10;
IDLER_BEARING_W = 4;
IDLER_BEARING_SHELF = 1.2;
BEARING_PRESS_FIT = -0.2;
TIRE_T = 12;
FUSE_T = 2;
FUSE_SHEAR_AREA = 10;
FUSE_ENABLE = true;
BED_X = 220;
BED_Y = 220;
BED_Z = 240;
NOZZLE = 0.4;
LAYER = 0.2;
FN = 64;

// Derived clearances (nominal thread + printing allowance).
SERVO_MOUNT_SCREW_CLEAR_D = 2.9;
SERVO_MOUNT_SCREW_HEAD_D = 5;
SERVO_MOUNT_SCREW_HEAD_H = 2.5;
SERVO_HORN_BOLT_CLEAR_D = 2.35;
