"""Custom environments. Importing this package registers them with Gymnasium.

train.py and watch.py do `import envs` for this side effect, after which
`gym.make("Spyder-v0")` works exactly like a built-in env id.

Two robots, each in a flat world and a desert one:

    Spyder-v0 / SpyderDesert-v0    12-DoF spider  (assets/spyder12*.xml)
    Hound-v0  / HoundDesert-v0     16-DoF wheel-legged dog (assets/hound16*.xml,
                                   generated by make_hound.py)

In both pairs the robot subtree is identical between the flat and desert
model, so the observation and action spaces match and a flat-world checkpoint
loads on the desert unchanged.
"""
from pathlib import Path

from gymnasium.envs.registration import register, registry

if "Spyder-v0" not in registry:
    register(
        id="Spyder-v0",
        entry_point="envs.spyder_env:SpyderEnv",
        # Truncation horizon: episodes end after 1000 steps (50 seconds at
        # 20 Hz) even if the spider is still healthy — same as Ant-v5.
        max_episode_steps=1000,
    )

if "Hound-v0" not in registry:
    register(
        id="Hound-v0",
        entry_point="envs.hound_env:HoundEnv",
        # 1000 steps at 20 Hz = 50 s, same horizon as every other env here.
        max_episode_steps=1000,
    )

if "HoundDesert-v0" not in registry:
    register(
        id="HoundDesert-v0",
        # Same env class, same spaces — only the world XML differs, so a
        # Hound-v0 checkpoint loads here unchanged.
        entry_point="envs.hound_env:HoundEnv",
        kwargs={
            "xml_file": str(
                Path(__file__).resolve().parent.parent
                / "assets"
                / "hound16_desert.xml"
            ),
        },
        max_episode_steps=1000,
    )

if "SpyderDesert-v0" not in registry:
    register(
        id="SpyderDesert-v0",
        # Same env class, same spaces — only the world XML differs (desert
        # heightfield instead of the plane), so Spyder-v0 checkpoints load
        # here unchanged. Terrain files come from make_terrain.py.
        entry_point="envs.spyder_env:SpyderEnv",
        kwargs={
            "xml_file": str(
                Path(__file__).resolve().parent.parent
                / "assets"
                / "spyder12_desert.xml"
            ),
        },
        max_episode_steps=1000,
    )
