"""HOUND-16 — generate the MJCF for a 16-DoF wheel-legged robot dog.

    python -m bestiary.robots.hound.build            # write both worlds
    python -m bestiary.robots.hound.build --report   # ...and print the DoF / mass / traction budget

Writes two models from one source of truth:

    assets/hound16.xml          flat plane  -> Hound-v0
    assets/hound16_desert.xml   desert hfield -> HoundDesert-v0  (same robot,
                                the terrain from terrain/generate.py under it)

The robot subtree is byte-identical between the two, so nq/nv/nbody and
therefore the observation and action spaces are unchanged and a flat-world
checkpoint loads on the desert directly — the same contract spyder12.xml and
spyder12_desert.xml have.


WHY A GENERATOR AND NOT A HAND-WRITTEN XML
------------------------------------------
spyder12.xml is hand-written because a 12-DoF spider is four copies of one
leg and the copies fit on a screen. This machine is four copies of a FOUR-link
leg whose stance angle is *solved*, not typed (see Spec.stance_knee), and it
ships in two worlds. Hand-maintaining that is four places to forget an edit.
The XML is generated, committed, and re-generated by re-running this file.


WHERE THE NUMBERS COME FROM
---------------------------
Link lengths, hip offsets and per-link masses are Unitree Go2's, read off
`unitree_go2/go2.xml` in MuJoCo Menagerie (Apache-2.0; the underlying Unitree
model is BSD-3). Using a real robot's inertial spec instead of invented
numbers means the mass distribution, the leg's reach-to-mass ratio and the
torque limits are all mutually consistent — a machine that could exist.

What is NOT from Unitree: the wheel. No vendor ships a wheel-legged MJCF, so
the fourth joint per leg is designed here, against the published envelope of
the wheeled quadrupeds that do exist (Unitree B2-W / Go2-W, ANYbotics
ANYmal-on-Wheels, Swiss-Mile): a direct-drive hub motor at the ankle, wheel
where the point foot used to be. The calf is shortened from Go2's 0.213 m to
0.190 m so that calf + wheel radius still lands near the original foot, and
the leg keeps roughly its original reach.


THE MORPHOLOGY: 4 LEGS x 4 JOINTS
---------------------------------
                    trunk  (free joint: 3 translations + 3 rotations)
                      |
      +---------------+---------------+
      |                               |
   FL_abduct (hinge, axis +X)     ... x4
      |
   FL_hip    (hinge, axis +Y)
      |
   FL_knee   (hinge, axis +Y)
      |
   FL_wheel  (hinge, axis +Y, UNLIMITED, no spring)

Three of the four are the spider's joints under different names: a yaw/roll
joint at the shoulder that swings the leg sideways, then two pitch joints in
the leg plane. The fourth is the wheel, and it is a genuinely different kind
of joint — the three reasons it needs its own treatment everywhere downstream:

  1. It never stops. `limited="false"`: its angle integrates without bound,
     so it is NOT a state you can feed a policy (envs/hound.py drops it
     from the observation and keeps only its velocity). Every other joint in
     this repo lives inside a range.
  2. It has no rest pose. The leg joints carry a spring toward the standing
     stance (`stiffness` + `springref`, see below); a spring on a wheel would
     mean the machine rolls back to where it started, which is nonsense.
  3. It is limited by the ground, not by the motor. With ~4.25 kgf on a
     wheel and mu = 0.9, the friction cone caps a wheel at 3.19 N*m, so
     gear_wheel is 3.0 and a bigger hub drive would buy nothing. The leg
     motors are sized by what they must *hold*; the wheel motors by what the
     ground will *accept*.

     robots/hound/check.py measures this and finds the conclusion right for the
     wrong reason, which is worth knowing before tuning anything. Thrust
     does saturate — 5x the gear gives LESS acceleration, not more — but it
     saturates at ~2 m/s^2, a quarter of the mu*g = 8.8 the friction cone
     would allow, with the cone only 5% used. What actually binds is a
     WHEELIE: all the thrust acts at ground level while the mass sits
     0.363 m up on a 0.387 m wheelbase, so hard driving pitches the machine
     onto its rear pair and past ~6 N*m lifts every wheel clear of the
     ground. Friction is the upper bound; geometry is the real one.

Axis convention: +X forward, +Y left, +Z up, meters, radians. Abduction uses
a single global axis (1 0 0) for all four legs rather than mirroring per
side — that is Unitree's own convention, so joint signs here match anything
you read in Go2 code. It does mean a symmetric action vector is not a
symmetric pose: +abduction swings the LEFT legs out and the RIGHT legs in.

Rest pose is all-zeros = legs straight down. The standing stance is a set of
joint angles (Spec.stance_*), applied as `springref` and as the env's
init_qpos, exactly like a qpos vector — nothing about the stance is baked
into geometry, so re-posing the machine is a number change here.


KNOWN LIMITATION: PASSIVE CREEP ON THE HEIGHTFIELD
--------------------------------------------------
Standing on the desert with every motor at zero, the machine drifts backwards
at roughly 5 cm/s. On the flat plane, under the identical model, it drifts
0.2 cm/s. The difference is the heightfield COLLIDER, not the terrain: the
spawn pad is exactly flat (0.000 mm peak-to-peak out to a 1.9 m radius, all
four wheels on identical cells), and swapping the hfield for a plane at the
same height removes the drift entirely.

The cause is a scale collision. MuJoCo collides a heightfield by testing the
geom against a prism per terrain cell, and the desert's cells are 7.82 cm
across — almost exactly the wheel's 8.5 cm radius. A wheel is therefore
always straddling a cell boundary, resolving against two prisms whose contact
normals do not quite agree, and the residual is a small net backward push.

Things that do NOT fix it, all measured: a sphere collider instead of a
cylinder, noslip_iterations up to 10, iterations=200, elliptic friction cones
(which cost 2.5x the wall clock and fell over MORE), and every solref between
0.004 and 0.02. Things that do help, and are applied: margin=0 and condim=3
(above), which cut the fall rate under noisy resets from 8/15 to 0/15, plus
the env's 5 mm spawn clearance.

Living with it is defensible — it is a force a policy holding station simply
has to counter, which is true of a real wheeled robot on a slope too.

CORRECTION, 2026-07-27 — THE CELL-SIZE STORY ABOVE IS WRONG, AND SO IS ITS
MAGNITUDE. Left standing rather than deleted, because the reasoning is worth
seeing: it is careful, specific, cites a real MuJoCo implementation detail,
and is still wrong. Full version in research/learnings/009.

This paragraph used to continue "The real fix is a finer heightfield:
regenerating terrain/generate.py at GRID=2048 would put four cells under each
wheel." Measured, 20 zero-action episodes per arm at one seed
(research/scripts/creep_vs_grid.py):

    GRID=1024   7.812 cm cells   -1.7761 +/- 0.0276 m per episode
    GRID=2048   3.906 cm cells   -1.7641 +/- 0.0066 m per episode
    paired difference            +11.99 +/- 26.18 mm  = 0.675% of the creep

Removing the creep needs +1776 mm. Halving the cell buys +12 mm.

The straddling mechanism was never available where the creep is generated.
terrain/generate.py blends the composed field to exactly zero inside a 2.5 m
radius, so the pad measures max|h| = 0.000e+00 and peak-to-peak = 0.000e+00
over 3212 cells, while every contact point across all 40 episodes landed
within 2.034 m. On exactly flat ground every prism normal is +z at ANY cell
size — four cells under a wheel are four cells of the same plane as one.
guards/spawn_pad.py now asserts that flatness, because the finding rests on it.

The magnitude was wrong too: the drift is -3.55 cm/s, not ~5 cm/s
(research/measurements/tracking_noise.json). 5 cm/s is not a rounding, it is
impossible beside the measured 0.0361 m/s rms planar speed — an rms speed
cannot be smaller than the magnitude of the mean velocity.

What survives: the hfield-versus-plane experiment above is real and still
implicates the heightfield COLLIDER. What died is the step from "the collider
does it" to "the collider does it VIA CELL SIZE" — an extra claim that
inherited the experiment's credibility without ever being measured. The creep
is unexplained again; do not replace one unmeasured mechanism with another.

(GRID=2048 is separately expensive: the regenerated desert correlates with the
committed one at only +0.061, so it is a different terrain rather than a
sharper one. See research/scripts/compare_terrain_grids.py.)
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

from bestiary import paths

ASSET_DIR = paths.ASSETS


class Spec:
    """Every dimension the machine is built from.

    Derived quantities are properties, never stored, so changing one length
    cannot leave a stale copy of itself in another constant.
    """

    # ── Trunk ────────────────────────────────────────────────────────────
    # Go2's base collision box (half-extents 0.1881 0.04675 0.057) and its
    # 6.921 kg body mass. The box is the whole chassis: battery, compute,
    # actuator drivers.
    trunk_half = (0.1881, 0.04675, 0.057)
    trunk_mass = 6.921

    # ── Leg attachment ───────────────────────────────────────────────────
    hip_x, hip_y = 0.1934, 0.0465   # abduction pivot in the trunk frame
    abduct_off = 0.0955             # abduction pivot -> hip pivot, along +/-Y

    # ── Link lengths ─────────────────────────────────────────────────────
    thigh_len = 0.213               # Go2, unchanged
    calf_len = 0.190                # Go2's 0.213, shortened to make room for
    wheel_r = 0.085                 # the wheel: 0.190 + 0.085 ~= 0.213 + foot
    wheel_w = 0.050                 # wheel width (full, not half)

    # ── Masses (kg) ──────────────────────────────────────────────────────
    # First three are Go2's. The wheel is a hub-motor estimate: a 170 mm
    # rim + stator at 0.45 kg is in line with the 2 kg-class hub drives on
    # wheeled quadrupeds, and deliberately a little heavy — a light wheel is
    # the easy case, and unsprung mass at the ankle is what makes wheeled
    # legs hard to control.
    hip_mass, thigh_mass, calf_mass, wheel_mass = 0.678, 1.152, 0.241, 0.45

    # ── Joint ranges (rad) ───────────────────────────────────────────────
    abduct_range = (-0.80, 0.80)    # +/-46 deg; Go2 allows +/-60
    hip_range = (-1.20, 2.60)
    knee_range = (-2.60, -0.60)     # knee only ever folds one way, like Go2's
    # The wheel has no range at all — see the module docstring.

    # ── Standing stance (rad) ────────────────────────────────────────────
    # hip is the input; the knee is SOLVED (see stance_knee) so the wheel
    # ends up directly under its own hip pivot. A stance with the contact
    # patch offset from the pivot pushes the machine sideways the moment it
    # takes weight, which reads as a drifting robot and is nobody's intent.
    stance_abduct = 0.0
    stance_hip = 0.75

    # ── Actuation ────────────────────────────────────────────────────────
    # ctrlrange is [-1, 1] everywhere (the repo convention), so `gear` IS the
    # peak joint torque in N*m. Leg values are Go2's rated torques; the knee
    # is scaled by our shorter calf (Go2 rates 45.43 N*m over 0.213 m).
    gear_abduct = 23.7
    gear_hip = 23.7
    gear_knee = 40.0
    # Wheel: see Spec.report(). 3.0 N*m sits just under the traction limit.
    gear_wheel = 3.0

    # ── PD position control (the HoundPD-v0 variant) ─────────────────────
    # Used only when build(control="pd"). The twelve leg joints become
    # position servos; the four wheels stay on torque, because a wheel that
    # spins forever has no pose to hold and a position target on it is
    # meaningless.
    #
    # kp in N*m/rad, kv in N*m/(rad/s). These are the gains the hand
    # controller in robots/hound/play.py already uses. They are the only
    # gains on this machine that have been shown to hold the stance and
    # re-pose it without fighting the physics into instability, so the PD
    # variant starts from them rather than from a fresh guess. See
    # docs/theory/pd-control.md for the damping-ratio check.
    kp_abduct = 60.0
    kp_hip = 80.0
    kp_knee = 90.0
    kv_abduct = 3.0
    kv_hip = 4.0
    kv_knee = 4.5

    # Radians either side of the standing stance that the policy may command.
    # The action stays in [-1, 1] (the repo convention) and the env maps it to
    # target = stance + action * action_scale, so a zero action IS the stance.
    # That is the whole prior: the policy starts at "standing" instead of
    # having to discover it.
    action_scale = 0.5

    # ── Joint dynamics ───────────────────────────────────────────────────
    armature = 0.01                 # Go2's reflected rotor inertia
    damping = 1.5
    frictionloss = 0.2
    # A spring toward the standing stance. NOT physical — real Go2 joints have
    # no springs — but the same crutch spyder12.xml uses (stiffness=30), and
    # for the same reason: it makes the machine self-supporting at reset, so
    # SAC spends its first 50k steps learning to move rather than learning to
    # not collapse.
    #
    # The stiffnesses are DERIVED, not typed (see static_torques / stiffness).
    # The first pass at this file guessed 6 / 12 / 12 N*m/rad and the machine
    # folded to a 0.18 m belly-flop the moment gravity was switched on: the
    # knee alone has to hold ~5 N*m in this stance, so 12 N*m/rad buys 0.4 rad
    # of droop per leg. Sizing from the free-body diagram instead makes the
    # sag a design input and the stiffness the output.
    #
    # sag_target is the whole trade. Stiffer = less droop at reset, but a
    # spring the motor has to fight also eats control authority, because the
    # joint's reachable band at full torque is springref +/- gear/stiffness.
    # With the springs preloaded (see springref) this is no longer a droop at
    # all — the machine stands exactly where it is drawn — but it still sets
    # the stiffnesses, and through them how much travel the motors keep.
    #
    # 0.16 rad is a floor, not a preference. The knee is the binding joint:
    # its reachable band is springref +/- gear/k = (stance + s) +/- 7.63*s,
    # and covering the full [-2.60, -0.60] range needs s >= 0.154. Anything
    # softer than that and the spring, not the mechanism, decides how far the
    # knee can straighten.
    sag_target = 0.16

    # ...and sag_target is not the only constraint, because a wheeled leg is
    # an INVERTED PENDULUM and holding a load is not the same as holding it
    # STABLY. See critical_stiffness() for the derivation; the short version
    # is that a spring merely strong enough to carry the static load lets the
    # machine slide into the splits, which is what the second draft of this
    # file did (front wheels rolled 15 cm forward, trunk fell to 0.25 m).
    #
    # So the hip spring is sized to this multiple of its stability threshold.
    # 1.6 is measured, not chosen: sweeping the hip against a passive settle,
    # a settle from a +/-0.1 rad noisy reset, and a 25 cm drop, the machine
    # first stands cleanly in all three at ~18 N*m/rad = 1.55x the 11.6
    # threshold. At exactly 1.0x it still folds — a critical stiffness is
    # where instability starts, not where stability is comfortable.
    #
    # The cost is real and is reported: the hip keeps ~2.5 rad of its 3.8 rad
    # range at full motor torque. That is far more than a gait needs, and the
    # metric is pessimistic anyway (it assumes the motor fights the spring
    # with no help from gravity or ground reaction), but it IS the price of
    # the crutch. Set the stiffnesses to 0 for the physically pure machine —
    # it then has to learn to stand up before it can learn to move.
    stability_margin = 1.6

    # Wheel-specific. Rotor inertia is LOW on a direct-drive hub (no gearbox
    # to reflect), and damping is low because a wheel is supposed to coast —
    # rolling resistance is modelled at the CONTACT (friction[2]), which is
    # where it physically comes from, not as joint damping, which would also
    # (wrongly) resist the wheel while it is in the air.
    wheel_armature = 0.004
    wheel_damping = 0.05
    # wheel frictionloss is DERIVED — see wheel_brake_torque().

    # ── Contact ──────────────────────────────────────────────────────────
    # MuJoCo friction is (sliding, torsional, rolling). The wheel sets
    # priority="1" so ITS numbers win over the floor's instead of the usual
    # element-wise max — a wheel's contact is a property of the tyre, and we
    # want the same tyre on the plane and on sand.
    #   sliding 0.9   traction; above this the wheel just spins
    #   torsional 0.03 resists pivoting about the contact normal. Without it a
    #                 standing machine can yaw for free on four point contacts.
    #   rolling 0.002 rolling resistance. This is the term that makes a
    #                 coasting wheel eventually stop, and it needs condim=6.
    wheel_friction = (0.9, 0.03, 0.002)
    # condim=3 (sliding only), so friction[1] and [2] above are inert. That is
    # deliberate and it cost a sweep to settle: condim=6 buys contact-level
    # torsional and rolling resistance, but on the DESERT it also settles 4 mm
    # lower and drifts twice as far, because every extra constraint per contact
    # is another chance for the heightfield's imperfect contact normals to
    # disagree with each other. Rolling resistance moves to the wheel joint
    # instead (wheel_brake_torque), where it is numerically boring and, for a
    # geared hub drive, arguably more honest anyway. The values are left in
    # place so switching back to condim=6 is a one-character experiment.
    wheel_condim = 3
    # margin=0, not the 1 mm used elsewhere. Margin makes contacts appear
    # BEFORE touchdown, and on a heightfield those early contacts are found
    # against the vertical walls of the terrain-cell prisms — normals pointing
    # sideways, into a wheel that is supposed to be rolling. At margin 0.001
    # the machine spawned with 11-18 horizontal-normal contacts and was kicked
    # over; at margin 0 it stands at 0.3630 with upright 1.000.
    wheel_margin = 0.0
    # Contact softness. This one line cost more debugging than everything
    # else in the file combined, so it gets the long comment.
    #
    # The first draft copied Go2's foot verbatim: solimp="0.015 1 0.022".
    # That is a deliberately SOFT contact — dmin=0.015 means the constraint
    # is nearly free at small penetration — and it is correct *for Go2*,
    # because go2.xml also sets <option cone="elliptic" impratio="100"/>,
    # which stiffens the normal direction back up. Copy the foot without the
    # option and you get the softness with none of the compensation: the
    # wheels sank 9 mm into the floor, the machine settled 8 cm low, pitched
    # 18 deg nose-up and dumped its rear thighs on the ground. Every spring
    # theory above was tested against that and came out wrong, because the
    # springs were never the problem.
    #
    # A firm contact instead. With this the machine settles 0.3 mm below the
    # height it is drawn at, which is the correct answer for a rigid wheel on
    # rigid ground, and it survives a 25 cm drop without grounding anything.
    wheel_solimp = (0.95, 0.99, 0.001)
    body_friction = (0.9, 0.5, 0.5)

    legs = {  # name: (x sign, y sign)
        "FL": (+1, +1),
        "FR": (+1, -1),
        "RL": (-1, +1),
        "RR": (-1, -1),
    }

    # ── Derived ──────────────────────────────────────────────────────────
    @property
    def stance_knee(self) -> float:
        """Knee angle that puts the wheel axle directly under the hip pivot.

        Forward kinematics in the leg's sagittal plane, with both pitch
        joints rotating about +Y. A rotation of theta about +Y maps the
        straight-down link vector (0, 0, -L) to (-L sin(theta), 0, -L cos(theta)),
        so positive pitch swings a link BACKWARD (-X) and up. Requiring zero
        net X offset at the axle:

            L_thigh * sin(hip) + L_calf * sin(hip + knee) = 0

        which inverts to knee = -asin(L_thigh sin(hip) / L_calf) - hip. The
        thigh's reach must be inside the calf's or there is no solution, hence
        the assert: that is the geometric statement "you cannot fold a long
        link back under a short one".
        """
        reach = self.thigh_len * math.sin(self.stance_hip)
        assert abs(reach) <= self.calf_len, (
            f"stance_hip={self.stance_hip} throws the knee {reach:.3f} m out, "
            f"which the {self.calf_len:.3f} m calf cannot pull back under the hip"
        )
        knee = -math.asin(reach / self.calf_len) - self.stance_hip
        assert self.knee_range[0] <= knee <= self.knee_range[1], (
            f"solved stance knee {knee:.3f} rad is outside {self.knee_range}"
        )
        return knee

    @property
    def axle_drop(self) -> float:
        """Hip pivot -> wheel axle, vertically, in the standing stance."""
        return self.thigh_len * math.cos(self.stance_hip) + self.calf_len * math.cos(
            self.stance_hip + self.stance_knee
        )

    @property
    def stand_z(self) -> float:
        """Trunk-origin height with the wheels resting on z = 0.

        The abduction pivots sit at the trunk origin's z, so this is just the
        axle drop plus the wheel radius. Written into the flat model's trunk
        `pos`; on the desert model HoundEnv re-bases it off the measured
        ground height, exactly as SpyderEnv does.
        """
        return self.axle_drop + self.wheel_r

    # ── Static analysis: what each spring actually has to hold ───────────
    #
    # All of this is one free-body diagram of a single leg carrying a quarter
    # of the machine, evaluated in the standing stance. It exists because the
    # alternative — guessing stiffnesses — produced a robot that folded flat.
    #
    # Leg-local coordinates: origin at the HIP pivot, +x forward, +z up, all
    # in the leg's sagittal plane. A pitch of theta about +Y maps (0,0,-L) to
    # (-L sin theta, 0, -L cos theta), the same convention stance_knee uses.
    def _leg_points(self) -> dict[str, tuple[float, float]]:
        t1 = self.stance_hip
        t2 = self.stance_hip + self.stance_knee
        knee = (-self.thigh_len * math.sin(t1), -self.thigh_len * math.cos(t1))
        axle = (knee[0] - self.calf_len * math.sin(t2),
                knee[1] - self.calf_len * math.cos(t2))
        return {
            "knee": knee,
            "axle": axle,
            "thigh_com": (knee[0] / 2.0, knee[1] / 2.0),
            "calf_com": ((knee[0] + axle[0]) / 2.0, (knee[1] + axle[1]) / 2.0),
            # The ground pushes up through the contact patch, which sits
            # directly below the axle — and, by stance_knee's construction,
            # directly below the hip pivot too.
            "contact": (axle[0], axle[1] - self.wheel_r),
        }

    def static_torques(self) -> dict[str, float]:
        """SIGNED gravity torque on each leg joint in the standing stance, N*m.

        The ground reaction on one wheel is a quarter of the machine's weight
        pushing straight up; every link's own weight pulls straight down. A
        joint's load is the net moment of everything distal to it.

        Signs matter here — they decide which way each spring must be wound
        (see springref) — so the moments are taken properly rather than as
        magnitudes. For the pitch joints, a vertical force F_z at a position
        r from the pivot makes a torque about +Y of -r_x * F_z. For abduction,
        which turns about +X, it is +r_y * F_z. Values are quoted for a LEFT
        leg; abduction mirrors with the leg's y sign, the other two do not.
        """
        g = 9.81
        p = self._leg_points()
        n = self.total_mass * g / 4.0        # ground reaction, one wheel

        # Knee: everything below it is the calf, the wheel, and the contact.
        knee = (
            -(p["contact"][0] - p["knee"][0]) * n
            - (p["calf_com"][0] - p["knee"][0]) * (-g * self.calf_mass)
            - (p["axle"][0] - p["knee"][0]) * (-g * self.wheel_mass)
        )

        # Hip: the ground reaction's line of action passes through the hip
        # pivot (contact x == 0), so it contributes NOTHING and all that is
        # left is the leg's own dead weight. That near-cancellation is the
        # whole point of solving for stance_knee — a stance with the wheel
        # offset from the hip would make this the largest load on the machine.
        hip = (
            -p["contact"][0] * n
            - p["thigh_com"][0] * (-g * self.thigh_mass)
            - p["calf_com"][0] * (-g * self.calf_mass)
            - p["axle"][0] * (-g * self.wheel_mass)
        )

        # Abduction turns about +X, so its lever arm is the sideways offset
        # from the abduction pivot, not the fore-aft one. Everything distal
        # hangs a full abduct_off outboard; the abduction link itself is a
        # bar spanning the offset, so its own weight acts at half of it.
        limb = self.thigh_mass + self.calf_mass + self.wheel_mass
        abduct = (
            self.abduct_off * (n - g * limb)
            + (self.abduct_off / 2.0) * (-g * self.hip_mass)
        )
        return {"abduct": abduct, "hip": hip, "knee": knee}

    def critical_stiffness(self) -> dict[str, float]:
        """Spring rate below which the standing stance is UNSTABLE, N*m/rad.

        THE defining mechanical difference between this machine and the
        spider, and the reason a wheel is not just "a foot that spins".

        A point foot grips. Push a legged robot's shin and the contact patch
        holds still, so the leg pivots about the FOOT and the geometry fights
        back. A wheel does not grip: it is free to roll, which means the
        contact patch is free to translate fore-aft. The leg therefore pivots
        about its own HIP with the ground offering no fore-aft resistance at
        all — a load balanced on a stick balanced on a cart.

        Formally: let h(q) be the height of the carried load above the contact
        patch. Gravitational potential is U = N*h, and an equilibrium is
        stable only where U is a local minimum. In the standing stance h is at
        a local MAXIMUM along the rolling directions (that is what "standing
        up" means), so d2U/dq2 is negative and the spring has to make up the
        difference. The joint is stable iff

            stiffness > -N * d2h/dq2                      [this function]

        Note what this does NOT apply to: abduction. A wheel is free along its
        rolling direction and grips across it, so the sideways lean the
        abduction joint controls still pivots about a contact patch that stays
        put. Exactly one of the three leg joints loses its passive stability,
        and it is the one whose motion rolls the wheel.

        This is also why the machine cannot simply stand: a real wheel-legged
        robot holds still by BRAKING its wheels, and a policy here has to
        learn the same thing. The springs only buy a stance at reset.
        """
        n = self.total_mass * 9.81 / 4.0
        t1 = self.stance_hip
        t2 = self.stance_hip + self.stance_knee
        # h = L1 cos(t1) + L2 cos(t1+t2) + r, differentiated twice.
        h_hip = -self.thigh_len * math.cos(t1) - self.calf_len * math.cos(t2)
        h_knee = -self.calf_len * math.cos(t2)
        return {"abduct": 0.0, "hip": -n * h_hip, "knee": -n * h_knee}

    def stiffness(self) -> dict[str, float]:
        """Spring rate per joint — the larger of two independent demands.

        Carry the static load within sag_target, AND clear the inverted-
        pendulum threshold with margin. report() prints both so it is visible
        which constraint sizes each joint: the knee and abduction are sized
        by load, the hip by stability, and nothing else is close.
        """
        crit = self.critical_stiffness()
        return {j: max(abs(t) / self.sag_target, self.stability_margin * crit[j])
                for j, t in self.static_torques().items()}

    def springref(self, y_sign: int = 1) -> dict[str, float]:
        """Spring rest angles — PRELOADED, not the stance itself.

        The bug this exists to fix is worth stating plainly, because it is
        invisible right up until the robot falls over. A spring produces zero
        torque at its own rest angle. Park springref ON the standing stance
        and the machine is released, at t=0, with every gram of its weight
        unopposed: ~5 N*m unbalanced at each knee. It drops, overshoots, and
        the hip's inverted-pendulum mode does the rest — the third draft of
        this file settled into a dog SIT, rear thighs flat on the floor,
        nose up 14 deg, and stiffer springs only made the sit deeper.

        So the springs are wound up in advance. Solving

            spring torque + gravity torque = 0   at   q = stance
            -k * (stance - springref) + tau_g = 0

        gives springref = stance - tau_g / k. And since k was defined as
        |tau_g| / sag_target, that offset is EXACTLY sag_target, wound
        AGAINST the direction gravity pulls:

            springref = stance + sign(-tau_g) * sag_target

        which is the whole idea in one line: wind each spring up by the
        deflection it would otherwise have sagged, and the authored stance
        becomes a true equilibrium — zero net torque, zero velocity, the
        machine simply stands there at the height it was drawn at.
        """
        tau, k = self.static_torques(), self.stiffness()
        tau = {**tau, "abduct": tau["abduct"] * y_sign}
        stance = {"abduct": self.stance_abduct, "hip": self.stance_hip,
                  "knee": self.stance_knee}
        return {j: stance[j] - tau[j] / k[j] for j in stance}

    def stability_deficit(self) -> dict[str, float]:
        """How much stiffness each joint is SHORT of stable, N*m/rad.

        Zero for every joint by construction — stiffness() takes the max with
        the threshold — so this exists as a self-check, asserted in report().
        """
        k, crit = self.stiffness(), self.critical_stiffness()
        return {j: max(0.0, crit[j] - k[j]) for j in crit}

    def wheel_brake_torque(self) -> float:
        """Breakaway torque of the hub drive, N*m.

        Not a stability device — the hip spring handles that, because the
        instability is the body rotating over a STATIONARY contact and a
        brake on the wheel does nothing about that. (An earlier draft of this
        file tried exactly that and it failed for precisely this reason: the
        wheels barely turned while the machine sat down around them.)

        Two jobs, one number. Physically it is the dry friction of a geared
        hub drive, and it is the ONLY thing that stops a coasting wheel now
        that condim=3 has removed contact-level rolling resistance — without
        it the machine would roll forever.

        The size, though, is set by the heightfield. 5% of rated torque is
        the plausible-hardware guess and it is enough on the flat plane; on
        the desert it is not, and 3/15 noisy resets ended on the floor. At
        13% every one of 15 stays up (upright >= 0.979) because a stiffer
        wheel shrugs off the impulsive kicks the hfield collider delivers
        instead of being spun down by them. So: partly hardware, partly
        numerics, and it would be dishonest to present it as purely the
        former. 13% breakaway is high for a direct-drive hub but ordinary
        for a geared one, so the machine it describes still exists.
        """
        return 0.133 * self.gear_wheel

    def is_stance_stable(self) -> tuple[bool, float]:
        """Positive-definiteness of the full (hip, knee) stiffness Hessian.

        The per-joint criterion above holds one joint while testing the other,
        but hip and knee are coupled — d2h/dhip.dknee is not zero — so a pair
        of individually-stable joints can still have an unstable mixed mode
        (the leg folding and swinging at once). The honest test is that

            K + N * d2h/dq2      for q = (hip, knee)

        is positive definite. Returns (ok, smallest eigenvalue).
        """
        n = self.total_mass * 9.81 / 4.0
        t1 = self.stance_hip
        t2 = self.stance_hip + self.stance_knee
        h11 = -self.thigh_len * math.cos(t1) - self.calf_len * math.cos(t2)
        h12 = -self.calf_len * math.cos(t2)
        h22 = -self.calf_len * math.cos(t2)
        k = self.stiffness()
        a, b, c = k["hip"] + n * h11, n * h12, k["knee"] + n * h22
        # Eigenvalues of the symmetric 2x2 [[a, b], [b, c]].
        mid = (a + c) / 2.0
        rad = math.sqrt(((a - c) / 2.0) ** 2 + b * b)
        lo = mid - rad
        return lo > 0.0, lo

    def authority(self) -> dict[str, float]:
        """Radians a motor at full torque can pull the joint off springref.

        The reachable band is springref +/- this. If it is narrower than the
        joint's own range, the spring — not the mechanism — is what limits
        the robot, which is a crutch that has become a cage.
        """
        gears = {"abduct": self.gear_abduct, "hip": self.gear_hip,
                 "knee": self.gear_knee}
        return {k: gears[k] / v for k, v in self.stiffness().items()}

    @property
    def total_mass(self) -> float:
        return self.trunk_mass + 4 * (
            self.hip_mass + self.thigh_mass + self.calf_mass + self.wheel_mass
        )

    @property
    def wheel_traction_torque(self) -> float:
        """Wheel torque at which the contact patch breaks loose, N*m.

        Static share of weight per wheel, times sliding friction, times the
        radius. This is the number that sizes gear_wheel: a hub motor geared
        past it cannot deliver more thrust, it can only spin.
        """
        normal = self.total_mass * 9.81 / 4.0
        return normal * self.wheel_friction[0] * self.wheel_r


SPEC = Spec()


# ── XML fragments ────────────────────────────────────────────────────────────
def leg_xml(spec: Spec, name: str, sx: int, sy: int) -> str:
    """One leg: abduct -> hip -> knee -> wheel, as a nested <body> chain.

    Every link is placed at its parent joint's pivot and runs along the
    link's own local axis, so the four legs differ ONLY in the (sx, sy)
    signs on the attachment point and the +/-Y side the abduction link
    reaches toward. There is no per-leg geometry.
    """
    x, y = sx * spec.hip_x, sy * spec.hip_y
    off = sy * spec.abduct_off
    lo_a, hi_a = spec.abduct_range
    lo_h, hi_h = spec.hip_range
    lo_k, hi_k = spec.knee_range
    hw = spec.wheel_w / 2.0
    k = spec.stiffness()
    ref = spec.springref(sy)   # preloaded; abduction mirrors with the y sign

    return f"""
      <!-- ══ {name} ══ -->
      <body name="{name}_abduct" pos="{x:.4f} {y:.4f} 0">
        <joint name="{name}_abduct" axis="1 0 0" range="{lo_a} {hi_a}"
               stiffness="{k['abduct']:.2f}" springref="{ref['abduct']:.6f}"/>
        <geom name="{name}_abduct_geom" type="capsule" size="0.040"
              fromto="0 0 0  0 {off:.4f} 0" mass="{spec.hip_mass}" rgba="0.20 0.21 0.24 1"/>
        <!-- Every hub is a cylinder ALONG ITS OWN JOINT AXIS, so the axis is
             readable from a still render: abduction turns about +X and is a
             barrel pointing fore-aft, while hip, knee and wheel all turn
             about +Y and are discs facing sideways. The first draft drew this
             one along +Y like the others, which made the shoulder look like
             two identical discs in different colours — the two joints there
             are 95 mm apart on PERPENDICULAR axes, and the picture said
             nothing about that. -->
        <geom class="hub" name="{name}_abduct_hub" type="cylinder" size="0.044"
              fromto="-0.040 0 0  0.040 0 0" material="MatAbduct"/>

        <body name="{name}_thigh" pos="0 {off:.4f} 0">
          <joint name="{name}_hip" axis="0 1 0" range="{lo_h} {hi_h}"
                 stiffness="{k['hip']:.2f}" springref="{ref['hip']:.6f}"/>
          <geom name="{name}_thigh_geom" type="capsule" size="0.028"
                fromto="0 0 0  0 0 {-spec.thigh_len:.4f}" mass="{spec.thigh_mass}"
                rgba="0.24 0.25 0.28 1"/>
          <geom class="hub" name="{name}_hip_hub" type="cylinder" size="0.042 0.014"
                fromto="0 -0.014 0  0 0.014 0" material="MatHip"/>

          <body name="{name}_calf" pos="0 0 {-spec.thigh_len:.4f}">
            <joint name="{name}_knee" axis="0 1 0" range="{lo_k} {hi_k}"
                   stiffness="{k['knee']:.2f}" springref="{ref['knee']:.6f}"/>
            <geom name="{name}_calf_geom" type="capsule" size="0.022"
                  fromto="0 0 0  0 0 {-spec.calf_len:.4f}" mass="{spec.calf_mass}"
                  rgba="0.20 0.21 0.24 1"/>
            <geom class="hub" name="{name}_knee_hub" type="cylinder" size="0.034 0.013"
                  fromto="0 -0.013 0  0 0.013 0" material="MatKnee"/>

            <!-- The wheel. Unlimited hinge, no spring, its own contact class.
                 The collision cylinder is the ONLY geom here that touches the
                 ground; the spokes and the tyre band are decoration. -->
            <body name="{name}_wheel" pos="0 0 {-spec.calf_len:.4f}">
              <joint class="wheel" name="{name}_wheel" axis="0 1 0"/>
              <geom class="tyre" name="{name}_wheel_geom" type="cylinder"
                    size="{spec.wheel_r}" fromto="0 {-hw} 0  0 {hw} 0"
                    mass="{spec.wheel_mass}"/>
              <geom class="hub" name="{name}_rim" type="cylinder"
                    size="{0.55 * spec.wheel_r:.4f}"
                    fromto="0 {-hw - 0.002:.4f} 0  0 {hw + 0.002:.4f} 0" material="MatWheel"/>
              <!-- Two spokes. Purely so the wheel's ROTATION is visible in a
                   render: a plain cylinder spinning about its own axis looks
                   identical at every angle, which makes it impossible to see
                   whether a policy is rolling or dragging. -->
              <geom class="hub" name="{name}_spoke_a" type="box"
                    size="{0.80 * spec.wheel_r:.4f} {hw + 0.003:.4f} 0.006"
                    material="MatSpoke"/>
              <geom class="hub" name="{name}_spoke_b" type="box"
                    size="0.006 {hw + 0.003:.4f} {0.80 * spec.wheel_r:.4f}"
                    material="MatSpoke"/>
            </body>
          </body>
        </body>
      </body>"""


def robot_xml(spec: Spec, trunk_z: float | None = None) -> str:
    """The trunk plus its four legs, identical in both worlds.

    `trunk_z` is where the trunk body is authored, in metres. None means
    `spec.stand_z` — wheels resting on z = 0 — which is what both MuJoCo worlds
    want and is why it is the default. Nothing in this repository passes
    anything else except the Isaac Lab conversion input.

    That override exists because Isaac Lab spawns a USD asset by creating a prim
    at `init_state.pos` and referencing the asset underneath it, so an authored
    trunk height is ADDED to the requested spawn height instead of replacing it.
    A 0.3634 m stance baked into the asset would put the machine 0.3634 m above
    where the caller asked for it and let it fall that far before the first
    reset writes a root pose. The stand height belongs to whoever places the
    robot, so `isaac/hound_usd.py` authors the trunk at the origin and
    `isaac/hound_cfg.py` supplies `spec.stand_z` as the spawn height.
    """
    hx, hy, hz = spec.trunk_half
    z = spec.stand_z if trunk_z is None else trunk_z
    legs = "".join(leg_xml(spec, n, sx, sy) for n, (sx, sy) in spec.legs.items())
    return f"""
    <body name="trunk" pos="0 0 {z:.4f}">
      <!-- Gymnasium's offscreen renderer looks up a camera named "track" when
           none is given (same as ant.xml); without it, eval videos fall back
           to a static free camera and the dog drives out of frame. -->
      <camera name="track" mode="trackcom" pos="0 -2.2 0.5" xyaxes="1 0 0 0 0.3 1"/>
      <joint name="root" type="free" armature="0" damping="0" stiffness="0" limited="false"/>

      <geom name="trunk_geom" type="box" size="{hx} {hy} {hz}" mass="{spec.trunk_mass}"
            rgba="0.22 0.23 0.26 1"/>
      <!-- Decoration only (class="deco": no mass, no contact). The head pod
           gives the machine a front, and the amber lens marks +X — the
           reward direction — so heading is readable in a still frame. Same
           trick as the spider's carapace lens. -->
      <geom class="deco" name="head_pod" type="box" size="0.055 0.052 0.040"
            pos="{hx + 0.035:.4f} 0 0.030" material="MatShell"/>
      <geom class="deco" name="head_lens" type="box" size="0.008 0.038 0.018"
            pos="{hx + 0.088:.4f} 0 0.034" material="MatLens"/>
      <geom class="deco" name="deck" type="box" size="{hx - 0.02:.4f} {hy - 0.004:.4f} 0.014"
            pos="-0.010 0 {hz + 0.012:.4f}" material="MatShell"/>
      <geom class="deco" name="tail_mast" type="capsule" size="0.007"
            fromto="{-hx - 0.01:.4f} 0 {hz:.4f}  {-hx - 0.07:.4f} 0 {hz + 0.075:.4f}"
            material="MatShell"/>
{legs}
    </body>"""


def actuator_xml(spec: Spec, control: str = "torque") -> str:
    """16 actuators, in the order the action vector uses.

    Per-leg blocks of four, legs in Spec.legs order. This block IS the
    contract for the action space — envs/hound.py's docstring quotes it,
    and robots/hound/check.py asserts the order.

    Two control modes, same 16 slots and same order in both:

    "torque"  every joint is a <motor>. ctrl is a fraction of peak torque,
              so `gear` IS the peak torque in N*m. What Hound-v0 uses.

    "pd"      the twelve leg joints become <position> servos: ctrl is a
              TARGET ANGLE in radians and MuJoCo runs
                  tau = kp * (target - q) - kv * qdot
              internally at the 200 Hz physics rate, TEN times per control
              step: frame_skip = 10 at timestep 0.005 s makes the policy act
              at 20 Hz, and 200 / 20 = 10. (This said "five" until 2026-07-28,
              when docs/lessons/scripts/pd_vs_torque_math.py read the two
              constants off the source instead of trusting the sentence.)
              The four wheels stay <motor>, because a wheel that turns
              forever has no pose to hold.

              forcerange keeps the same Go2 torque ceiling the torque model
              has, so the machine is no easier to drive — only easier to
              command.

              ctrlrange is each joint's own travel, written explicitly rather
              than via inheritrange: the <motor ctrlrange="-1 1"> default in
              common_head applies to every actuator type, not just <motor>,
              and MuJoCo rejects a model that sets both.
    """
    if control not in ("torque", "pd"):
        raise ValueError(f"control must be 'torque' or 'pd', got {control!r}")

    lo_a, hi_a = spec.abduct_range
    lo_h, hi_h = spec.hip_range
    lo_k, hi_k = spec.knee_range

    rows = []
    for name in spec.legs:
        if control == "torque":
            rows.append(f'    <motor name="{name}_abduct" joint="{name}_abduct" '
                        f'gear="{spec.gear_abduct}"/>')
            rows.append(f'    <motor name="{name}_hip"    joint="{name}_hip"    '
                        f'gear="{spec.gear_hip}"/>')
            rows.append(f'    <motor name="{name}_knee"   joint="{name}_knee"   '
                        f'gear="{spec.gear_knee}"/>')
        else:
            rows.append(f'    <position name="{name}_abduct" joint="{name}_abduct" '
                        f'kp="{spec.kp_abduct}" kv="{spec.kv_abduct}" '
                        f'ctrlrange="{lo_a} {hi_a}" '
                        f'forcerange="-{spec.gear_abduct} {spec.gear_abduct}"/>')
            rows.append(f'    <position name="{name}_hip"    joint="{name}_hip"    '
                        f'kp="{spec.kp_hip}" kv="{spec.kv_hip}" '
                        f'ctrlrange="{lo_h} {hi_h}" '
                        f'forcerange="-{spec.gear_hip} {spec.gear_hip}"/>')
            rows.append(f'    <position name="{name}_knee"   joint="{name}_knee"   '
                        f'kp="{spec.kp_knee}" kv="{spec.kv_knee}" '
                        f'ctrlrange="{lo_k} {hi_k}" '
                        f'forcerange="-{spec.gear_knee} {spec.gear_knee}"/>')
        rows.append(f'    <motor name="{name}_wheel"  joint="{name}_wheel"  '
                    f'gear="{spec.gear_wheel}"/>')
    return "\n".join(rows)


def keyframe_xml(spec: Spec) -> str:
    """The standing stance, shipped as a MuJoCo keyframe.

    envs/hound.py reads init_qpos straight out of this rather than
    recomputing the stance from Spec, so the pose the env spawns and the pose
    the springs are wound against can never drift apart — the XML is the one
    place both of them read. (Go2 ships its crouch the same way, as
    <key name="home">.)
    """
    q = [0.0, 0.0, spec.stand_z, 1.0, 0.0, 0.0, 0.0]
    for _ in spec.legs:
        q += [spec.stance_abduct, spec.stance_hip, spec.stance_knee, 0.0]
    return ('  <keyframe>\n    <key name="stance" qpos="'
            + " ".join(f"{v:.6g}" for v in q) + '"/>\n  </keyframe>')


def common_head(spec: Spec, model: str) -> str:
    """compiler / option / default / materials — shared by both worlds."""
    fs, ft, fr = spec.body_friction
    ws, wt, wr = spec.wheel_friction
    si0, si1, si2 = spec.wheel_solimp
    # inertiafromgeom="true": every body's inertia tensor is derived from its
    # geoms' SHAPES, scaled to the explicit `mass` on each geom. So the mass
    # budget stays readable as one number per link (Go2's real values) while
    # the inertia stays consistent with the geometry that number is spread
    # over — no hand-written 3x3s to drift out of sync with a length change.
    # The deco/hub classes carry density="0" and no mass, so they contribute
    # exactly nothing here.
    return f"""  <compiler angle="radian" coordinate="local" inertiafromgeom="true"/>
  <!-- integrator: implicitfast, NOT the RK4 the rest of this repo uses.
       RK4 evaluates the dynamics four times per step and treats damping
       explicitly, which is exactly the wrong trade for a machine whose
       fastest state is a lightly-damped wheel that can pass 40 rad/s.
       implicitfast integrates joint damping and armature implicitly, so the
       wheel stays stable at a timestep where RK4 rings. One eval per step at
       0.005 s is also CHEAPER than four evals at 0.01 s.
       timestep 0.005 with frame_skip=10 gives the same 20 Hz control rate as
       every other env here, over 200 Hz physics. -->
  <option integrator="implicitfast" timestep="0.005"/>

  <!-- Offscreen buffer for HD eval videos and for robots/hound/render.py. MuJoCo
       defaults to 640x480 and REFUSES a larger render rather than scaling,
       so this has to be declared here, in both worlds. -->
  <visual>
    <global offwidth="1920" offheight="1088"/>
    <quality shadowsize="4096"/>
  </visual>

  <default>
    <!-- Leg joints. stiffness/springref are set per-joint (the stance differs
         per joint); everything else is shared. -->
    <joint type="hinge" limited="true" armature="{spec.armature}"
           damping="{spec.damping}" frictionloss="{spec.frictionloss}"/>
    <geom condim="3" friction="{fs} {ft} {fr}" margin="0.001" group="0"/>
    <motor ctrllimited="true" ctrlrange="-1 1"/>

    <!-- The wheel hinge: unlimited, no spring, low rotor inertia. Everything
         about this class exists because a wheel is not a joint with a pose. -->
    <default class="wheel">
      <joint type="hinge" limited="false" stiffness="0"
             armature="{spec.wheel_armature}" damping="{spec.wheel_damping}"
             frictionloss="{spec.wheel_brake_torque():.4f}"/>
    </default>

    <!-- The tyre. priority=1 makes these friction values win outright over
         whatever surface it meets, instead of MuJoCo's default element-wise
         max — so the same tyre behaves the same on the plane and on sand.
         condim=6 is required for friction[2] (rolling resistance) to exist at
         all; at condim=3 a coasting wheel would roll forever. -->
    <default class="tyre">
      <geom condim="{spec.wheel_condim}" priority="1"
            friction="{ws} {wt} {wr}" solimp="{si0} {si1} {si2}"
            margin="{spec.wheel_margin}" material="MatTyre"/>
    </default>

    <!-- Visual-only geometry. density=0 AND mass unset so it adds nothing to
         the inertia; contype/conaffinity=0 so it never makes a contact. The
         physics is exactly what it would be with these deleted — the same
         invariant robots/spyder/check.py enforces for the spider's shell. -->
    <default class="deco">
      <geom contype="0" conaffinity="0" density="0" group="2"/>
    </default>
    <default class="hub">
      <geom contype="0" conaffinity="0" density="0" group="2"/>
    </default>
  </default>

  <asset>
    <!-- Joint colour code, same reading order as the spider: the hub at a
         joint tells you which axis it turns about. red = abduction (roll,
         +X), green = hip (pitch, +Y), blue = knee (pitch, +Y), amber = wheel. -->
    <material name="MatShell"  rgba="0.17 0.18 0.21 1" specular="0.6" shininess="0.55" reflectance="0.10"/>
    <material name="MatAbduct" rgba="0.76 0.17 0.16 1" specular="0.5" shininess="0.40"/>
    <material name="MatHip"    rgba="0.15 0.65 0.25 1" specular="0.5" shininess="0.40"/>
    <material name="MatKnee"   rgba="0.20 0.40 0.85 1" specular="0.5" shininess="0.40"/>
    <material name="MatWheel"  rgba="0.82 0.55 0.12 1" specular="0.7" shininess="0.60"/>
    <material name="MatSpoke"  rgba="0.55 0.57 0.62 1" specular="0.7" shininess="0.60"/>
    <material name="MatTyre"   rgba="0.09 0.09 0.10 1" specular="0.15" shininess="0.10"/>
    <material name="MatLens"   rgba="0.95 0.62 0.15 1" specular="0.9" shininess="0.90" emission="0.45"/>
{{extra_assets}}  </asset>
"""


FLAT_WORLD = """  <asset>
    <texture builtin="gradient" height="100" rgb1="0.36 0.50 0.72" rgb2="0.82 0.86 0.92"
             type="skybox" width="100"/>
    <texture name="texplane" type="2d" builtin="checker" rgb1="0.24 0.25 0.27"
             rgb2="0.31 0.32 0.35" width="512" height="512"/>
    <material name="MatPlane" texture="texplane" texrepeat="20 20" reflectance="0.08"/>
  </asset>

  <worldbody>
    <light cutoff="100" diffuse="1 0.98 0.94" dir="0.35 0.25 -0.90" directional="true"
           exponent="1" pos="0 0 6" mode="trackcom" specular="0.15 0.15 0.15"/>
    <geom name="floor" type="plane" size="40 40 0.1" material="MatPlane"
          condim="3" conaffinity="1" group="0" friction="1 0.5 0.5"/>
"""


DESERT_WORLD = """  <worldbody>
    <light cutoff="100" diffuse="1 0.96 0.88" dir="0.45 0.25 -0.86" directional="true"
           exponent="1" pos="0 0 10" mode="trackcom" specular=".1 .1 .1"/>
    <!-- The desert floor from terrain/generate.py, reused verbatim from
         spyder12_desert.xml: same .bin, same texture, same pos z = the
         generator's printed h_min so the spawn pad sits at world z = 0.
         Ground friction is the sand value (0.8), but the tyre's priority=1
         overrides it at the contact — see the "tyre" default class. -->
    <geom name="floor" type="hfield" hfield="desert" material="MatDesert"
          pos="0 0 -0.41" condim="3" conaffinity="1" group="0" friction="0.8 0.5 0.5"/>
"""

DESERT_ASSETS = """    <texture builtin="gradient" height="100" rgb1="0.40 0.60 0.85" rgb2="0.87 0.78 0.62"
             type="skybox" width="100"/>
    <hfield name="desert" file="terrain/desert_hfield.bin" size="40 40 5.05 1.0"/>
    <texture name="texdesert" type="2d" file="terrain/desert_texture.png"/>
    <material name="MatDesert" texture="texdesert" texrepeat="1 1" texuniform="false"
              reflectance="0.05" shininess="0.05" specular="0.2"/>
"""

DESERT_VISUAL = """  <visual>
    <!-- 8k shadow map, up from the shared 4k: a directional light's shadow
         has to stretch across the whole 80 m heightfield, and at 4k the
         texels are large enough to speckle the ground with acne. -->
    <quality shadowsize="8192"/>
    <map haze="0.15"/>
    <rgba haze="0.89 0.80 0.65 1"/>
  </visual>

  <!-- Pin the shadow volume to robot scale: a directional light's shadow map
       is an orthographic box sized by the model extent, which the 80 m
       heightfield would otherwise inflate until robot-scale shadows dissolve.
       8 m, not the 4 m tried first — too TIGHT is also a failure, and a
       noisier one: at extent=4 the depth bias scales down with the volume
       until the ground starts self-shadowing, and the desert renders with a
       moire of shadow acne across the foreground (measured high-frequency
       ground noise 84.8 at extent 4, 0.8 at extent 8). Purely a rendering
       parameter — a settle test with the whole element deleted is identical. -->
  <statistic extent="8" center="0 0 0.4"/>
"""


def build(spec: Spec, desert: bool, control: str = "torque") -> str:
    stem = "hound16" if control == "torque" else "hound16pd"
    model = f"{stem}_desert" if desert else stem
    header = (
        "Hound-Desert-v0: the SAME hound16 robot on the procedural desert\n"
        "       heightfield (terrain/generate.py). The robot subtree below is generated\n"
        f"       from the same Spec as assets/{stem}.xml, so nq/nv/nbody and\n"
        "       therefore the whole observation and action space are unchanged and a\n"
        "       flat-world checkpoint loads here directly. Only the ground changed."
        if desert else
        "Hound-v0: a 16-DoF wheel-legged robot dog on a flat plane.\n"
        "       Four legs, four joints each: abduction (roll) + hip (pitch) +\n"
        "       knee (pitch) + WHEEL (unlimited spin at the ankle)."
    )
    head = common_head(spec, model).format(
        extra_assets=DESERT_ASSETS if desert else ""
    )
    return f"""<mujoco model="{model}">
  <!-- GENERATED BY robots/hound/build.py — DO NOT EDIT BY HAND.
       Re-generate with `python -m bestiary.robots.hound.build`; change the numbers in that
       file's Spec class, not here.

       {header}
  -->
{head}{DESERT_VISUAL if desert else ""}
{DESERT_WORLD if desert else FLAT_WORLD}{robot_xml(spec)}
  </worldbody>

  <actuator>
{actuator_xml(spec, control)}
  </actuator>

{keyframe_xml(spec)}
</mujoco>
"""


# ── Report ───────────────────────────────────────────────────────────────────
def report(spec: Spec) -> None:
    """Print the budgets a reader would otherwise have to derive by hand."""
    deg = math.degrees
    nq = 7 + 16
    nv = 6 + 16
    nbody = 1 + 4 * 4          # trunk + 4 legs x (abduct, thigh, calf, wheel)
    reserved = 28          # 3 command + 25 height, zero in v0
    obs = (nq - 2 - 4) + nv + nbody * 6 + reserved

    print("── HOUND-16 ──────────────────────────────────────────────────────")
    print("  4 legs x (abduct + hip + knee + wheel) = 16 actuated DoF")
    print("  + 6 unactuated DoF from the trunk's free joint")
    print()
    print("  Standing stance")
    print(f"    abduct  {spec.stance_abduct:+.4f} rad ({deg(spec.stance_abduct):+6.1f} deg)  input")
    print(f"    hip     {spec.stance_hip:+.4f} rad ({deg(spec.stance_hip):+6.1f} deg)  input")
    print(f"    knee    {spec.stance_knee:+.4f} rad ({deg(spec.stance_knee):+6.1f} deg)  SOLVED: axle under hip")
    print(f"    hip -> axle drop  {spec.axle_drop:.4f} m")
    print(f"    trunk stand height {spec.stand_z:.4f} m  (axle drop + wheel r)")
    print()
    print("  Mass budget")
    for label, m, n in (
        ("trunk", spec.trunk_mass, 1),
        ("abduct link", spec.hip_mass, 4),
        ("thigh", spec.thigh_mass, 4),
        ("calf", spec.calf_mass, 4),
        ("wheel", spec.wheel_mass, 4),
    ):
        print(f"    {label:<12} {m:6.3f} kg x{n}  = {m * n:6.3f} kg")
    print(f"    {'TOTAL':<12} {spec.total_mass:6.3f} kg")
    print()
    print("  Spring sizing")
    tau = spec.static_torques()
    crit = spec.critical_stiffness()
    deficit = spec.stability_deficit()
    stiff, auth = spec.stiffness(), spec.authority()
    ranges = {"abduct": spec.abduct_range, "hip": spec.hip_range,
              "knee": spec.knee_range}
    refs = spec.springref(+1)
    stance = {"abduct": spec.stance_abduct, "hip": spec.stance_hip,
              "knee": spec.stance_knee}
    print(f"    {'joint':<8}{'holds':>8}{'spring k':>9}{'stab k':>9}{'stance':>8}"
          f"{'springref':>10}{'authority':>10}  reachable vs range")
    for j in ("abduct", "hip", "knee"):
        lo, hi = ranges[j]
        band = (refs[j] - auth[j], refs[j] + auth[j])
        frac = (min(hi, band[1]) - max(lo, band[0])) / (hi - lo)
        covers = "full range" if frac >= 1.0 else f"{100 * frac:.0f}% of range"
        load_k = abs(tau[j]) / spec.sag_target
        note = ("sized by LOAD" if load_k >= spec.stability_margin * crit[j]
                else "sized by STABILITY")
        assert deficit[j] == 0.0, f"{j} is short {deficit[j]:.2f} of stable"
        print(f"    {j:<8}{tau[j]:+7.2f}N{stiff[j]:9.1f}{crit[j]:9.1f}"
              f"{stance[j]:+8.2f}{refs[j]:+10.2f}{auth[j]:9.2f}r  "
              f"[{band[0]:+.2f},{band[1]:+.2f}] vs [{lo:+.2f},{hi:+.2f}] "
              f"{covers:<18} {note}")
    print("    holds    = SIGNED gravity torque at the stance")
    print(f"    springref= stance wound {spec.sag_target} rad AGAINST it, so the "
          f"spring already carries `holds` at the stance (t=0 is an equilibrium)")
    print(f"    spring k = |holds| / sag_target ({spec.sag_target} rad = "
          f"{deg(spec.sag_target):.1f} deg); LOAD ONLY, so the motor keeps its travel")
    print(f"    stab k   = {spec.stability_margin} x the inverted-pendulum threshold")
    print("               -N*d2h/dq2. Abduction is exempt: a wheel rolls fore-aft")
    print("               but GRIPS sideways, so only the hip loses its stability.")
    ok, lo_eig = spec.is_stance_stable()
    print(f"    coupled (hip,knee) Hessian min eigenvalue {lo_eig:+.2f} -> "
          f"{'STABLE' if ok else 'UNSTABLE'}")
    print()
    print("  Wheel torque budget  (why gear_wheel is small)")
    normal = spec.total_mass * 9.81 / 4.0
    print(f"    static load per wheel      {normal:6.2f} N  ({normal / 9.81:.2f} kgf)")
    print(f"    max friction, mu={spec.wheel_friction[0]}       "
          f"{normal * spec.wheel_friction[0]:6.2f} N")
    print(f"    -> traction limit          {spec.wheel_traction_torque:6.2f} N*m "
          f"at r={spec.wheel_r} m")
    print(f"    gear_wheel                 {spec.gear_wheel:6.2f} N*m  "
          f"({100 * spec.gear_wheel / spec.wheel_traction_torque:.0f}% of the limit)")
    thrust = 4 * spec.gear_wheel / spec.wheel_r
    print(f"    all four at full torque    {thrust:6.2f} N thrust  -> "
          f"{thrust / spec.total_mass:.2f} m/s^2 IDEAL")
    wheelie = spec.total_mass * 9.81 * spec.hip_x / spec.stand_z
    print(f"    ...but the wheelie limit   {wheelie:6.2f} N  -> "
          f"{wheelie / spec.total_mass:.2f} m/s^2  (thrust acts at ground level,"
          f" mass sits {spec.stand_z:.2f} m up on a {2 * spec.hip_x:.3f} m wheelbase)")
    print("    measured saturation        ~2.0 m/s^2 (robots/hound/check.py) — geometry")
    print("                               binds before friction does")
    print()
    print("  Spaces")
    print(f"    nq {nq}   nv {nv}   nbody(non-world) {nbody}   nu 16")
    print(f"    obs = (nq-2-4) + nv + nbody*6 + reserved = "
          f"{nq - 2 - 4} + {nv} + {nbody * 6} + {reserved} = {obs}")
    print("         ^ -2 drops world x,y (position-invariant locomotion)")
    print("         ^ -4 drops the WHEEL ANGLES: unbounded integrators, see")
    print("           envs/hound.py. Their velocities are kept.")
    print(f"         ^ +{reserved} RESERVED slots (3 command + 25 height scan),")
    print("           held at zero in v0 so a later roadmap step cannot")
    print("           change the observation width and orphan every checkpoint.")
    print("──────────────────────────────────────────────────────────────────")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--report", action="store_true",
                    help="print the DoF / mass / traction budget")
    ap.add_argument("--out-dir", type=Path, default=ASSET_DIR)
    ap.add_argument("--control", choices=("torque", "pd", "both"), default="both",
                    help="which actuator variant to write (default: both)")
    args = ap.parse_args()

    modes = ("torque", "pd") if args.control == "both" else (args.control,)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for control in modes:
        stem = "hound16" if control == "torque" else "hound16pd"
        for desert in (False, True):
            path = args.out_dir / (f"{stem}_desert.xml" if desert else f"{stem}.xml")
            path.write_text(build(SPEC, desert, control))
            print(f"wrote {path}")

    if args.report:
        print()
        report(SPEC)


if __name__ == "__main__":
    main()
