"""Isaac Lab actuator and articulation config for WHELP-16.

GENERATED by `python -m bestiary.robots.whelp.urdf_gen`. DO NOT EDIT.

WHY THIS FILE EXISTS AT ALL
---------------------------
A URDF cannot express three things this robot depends on:

  1. That the twelve leg joints are POSITION-controlled and the four wheels are
     VELOCITY-controlled. There is no URDF tag for it, and getting it wrong is
     not a subtle degradation: a position target on a `continuous` joint fails
     in PhysX once the accumulated command passes +/-2*pi, i.e. after about
     three revolutions of driving.

  2. Reflected rotor inertia. At 1:345 the STS3215 presents
     0.027 kg.m^2 at the joint, roughly a hundred times
     the thigh's own inertia. Leave it out and the simulated leg is a nearly
     massless whip that a policy will flick at rates the real leg cannot reach.
     It is the most-omitted parameter in hobby-robot URDFs and on a machine this
     light it dominates.

  3. That effort_limit and velocity_limit are IGNORED by ImplicitActuatorCfg.
     The ones the solver enforces are effort_limit_sim and velocity_limit_sim.
     Setting only the first pair is a config that looks correct, changes
     nothing, and lets the policy learn joint speeds the servo does not have.

THE ACTUATOR IS NOT AN EFFORT SOURCE
------------------------------------
The STS3215 has four operating modes -- position, constant speed, open-loop PWM,
and step -- and no torque or current mode at all. The policy emits a POSITION
TARGET and the servo closes its own loop internally, at its own rate, with
firmware integer gains (P=32, D=32, I=0 by default), its own deadband and its own
saturation. An ideal-effort actuator model in simulation is therefore a model of
a robot nobody owns, and that mismatch is the classic cause of "it worked in
simulation".

stiffness and damping below are a STARTING POINT, not an identification. There is
no published mapping from the firmware's integer P/D to N.m/rad. Fit them to a
measured step response on a real servo at your real bus voltage before a long run,
and expect two units from one batch to differ.
"""
import math

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

# Solved standing stance. The knee is NOT typed: geometry.solve_stance_knee()
# places the wheel axle directly under the hip pivot, which makes the hip's
# static holding torque exactly zero.
STANCE = {
    ".*_abduct": 0.000000,
    ".*_hip": 0.460000,
    ".*_knee": -0.970190,
    ".*_wheel": 0.0,
}

#: Trunk-origin height with the wheels resting on the ground, at the LOADED wheel
#: radius. Spawning at the free radius puts the robot into the floor, and PhysX
#: resolves that by launching it.
STAND_HEIGHT = 0.229431

WHELP16_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path="{USD_PATH}",   # produced by scripts/tools/convert_urdf.py
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=10.0,
            # NOTE: documented in DEGREES per second while max_linear_velocity
            # next to it is m/s. Any number that looks wrong by 57.3x is this.
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, STAND_HEIGHT),
        joint_pos=STANCE,
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        # ── The twelve leg joints: POSITION control ──────────────────────────
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[".*_abduct", ".*_hip", ".*_knee"],
            effort_limit_sim=2.9420,
            velocity_limit_sim=4.7124,
            stiffness={".*": 8.0},
            damping={".*": 0.4},
            armature={".*": 0.027000},
            friction={".*": 0.068000},
        ),
        # ── The four wheels: VELOCITY control ────────────────────────────────
        # stiffness MUST be zero. A non-zero position gain on a continuous joint
        # is the failure described at the top of this file.
        "wheels": ImplicitActuatorCfg(
            joint_names_expr=[".*_wheel"],
            effort_limit_sim=2.9420,
            velocity_limit_sim=4.7124,
            stiffness={".*": 0.0},
            damping={".*": 0.6},
            armature={".*": 0.027000},
            friction={".*": 0.030000},
        ),
    },
)

# ── The envelope this hardware actually has ─────────────────────────────────
# These are not advisory. They are what the machine can do, and a policy trained
# outside them cannot be run on it.
#
#   top speed              0.21 m/s   (wheel drive, no load)
#   leg joint rate         4.71 rad/s   about a sixth of what
#                                    published legged-RL configs assume
#   design drop height     8 mm     above this the knee is over
#                                    its peak rating; the gearbox cannot yield
#                                    on impact timescales, so it goes into plastic
#
# The control loop is bounded by FEEDBACK, not commands: a broadcast sync-write
# to sixteen servos returns nothing and is fast, while a sync-read serialises
# sixteen replies on one half-duplex wire. Train at 50 Hz decimation and treat
# anything faster as headroom you have not measured.
MAX_SPEED_M_S = 0.2055
MAX_JOINT_RATE_RAD_S = 4.7124
DESIGN_DROP_M = 0.0080
CONTROL_HZ = 50.0
