"""Guard: every checkpoint still loads into the env that produced it.

Enforces `research/learnings/003` (changing the observation list throws away
every checkpoint).

The actor's first layer is `Linear(obs, 256)`, so a checkpoint trained at 113
observations does not degrade when the env moves to 141 — `SAC.load()` raises
and the run is gone. The failure surfaces hours later, at resume time, as a
shape error with no hint that an env edit three days ago caused it.

This reads the shapes out of the checkpoint's `data` member, which is plain
JSON inside the zip, so no torch import and no GPU. Comparing against a live
`gym.make()` costs one MuJoCo model load per distinct env id.

## Runs whose door was already walked through

Some checkpoints are permanently, correctly dead: the observation moved, or the
env id no longer exists. Re-reporting them as fresh failures forever is worse
than useless, because `guards --fast` gates every training launch — one
historical orphan would block all future work, and the pressure would be to
stop running the guard rather than to fix anything.

So an orphan is **declared** in `research/retired_runs.jsonl`
(`python -m bestiary.record.retire`), and this guard then asserts the stronger
pair: every undeclared run loads, **and every declared orphan really is dead**.
A declaration that becomes loadable again is a FAIL, not a pass — which is what
stops the file being a way to mute the guard. See `record/retire.py` for the
writer, which refuses to retire anything that still loads.
"""
from __future__ import annotations

import json
import zipfile
from functools import cache

from bestiary import paths
from bestiary.guards import Finding

CHECKPOINTS = ("ant_sac.zip", "ant_sac_best.zip")


@cache
def _env_shapes(env_id: str) -> tuple[int, int]:
    """(observation width, action width) of a freshly built env.

    Cached because building the desert envs loads a heightfield, and several
    runs share an env id.
    """
    import gymnasium as gym

    import bestiary.envs  # noqa: F401  — registers the ids as an import side effect

    env = gym.make(env_id)
    try:
        return int(env.observation_space.shape[0]), int(env.action_space.shape[0])
    finally:
        env.close()


@cache
def _env_obs_spec(env_id: str):
    """The live `ObsSpec` for an env id. Cached for the same reason as above."""
    import gymnasium as gym

    import bestiary.envs  # noqa: F401  — registers the ids

    env = gym.make(env_id)
    try:
        return env.unwrapped._obs_spec
    finally:
        env.close()


def _checkpoint_shapes(zip_path) -> tuple[int, int]:
    with zipfile.ZipFile(zip_path) as z:
        data = json.loads(z.read("data").decode())
    return (
        int(data["observation_space"]["_shape"][0]),
        int(data["action_space"]["_shape"][0]),
    )


def _retired() -> dict[str, dict]:
    """run name -> its declaration row, from `research/retired_runs.jsonl`.

    Deliberately the WRITER's parser, imported rather than reimplemented. Two
    parsers for one record file is the bug class where reader and writer
    quietly disagree about what a row means and nothing ever surfaces it.
    """
    from bestiary.record.retire import read_rows

    return read_rows()


def run() -> list[Finding]:
    if not paths.RUNS.exists():
        # n=0, not None: this is the guard's whole output on a fresh clone, and
        # it quantified over zero runs. VACUOUS is what that should read as.
        return [Finding("runs/ exists", True, "no runs yet — nothing to check", n=0)]

    findings: list[Finding] = []
    checked = 0
    unpinned: list[str] = []
    pinned: list[str] = []

    try:
        retired = _retired()
    except ValueError as exc:
        return [Finding("retired_runs.jsonl parses", False, str(exc), n=None)]

    for run_dir in sorted(p for p in paths.RUNS.iterdir() if p.is_dir()):
        config_path = run_dir / "config.json"
        if not config_path.exists():
            continue
        try:
            config = json.loads(config_path.read_text())
        except json.JSONDecodeError as exc:
            # Per-run and per-checkpoint findings below carry n=1: each is one
            # of a series generated by iterating runs/ (or a run's checkpoints)
            # and it really did examine one named artifact. n=None is reserved
            # for assertions with no input set at all — otherwise an assertion
            # could hide from the vacuity audit by declaring itself unquantified.
            findings.append(
                Finding(f"{run_dir.name}: config is readable", False, str(exc), n=1)
            )
            continue
        if "env_id" not in config:
            # Not every run under runs/ is a SAC run: the NTP transformer runs
            # (bestiary/ntp) write their own config schema — no env_id, no
            # ant_sac*.zip. Learning 003's width contract is about SAC
            # checkpoints reloading into gym envs, so those runs are outside
            # this guard — NAMED as such, never silently skipped, and still a
            # FAIL if SAC checkpoints sit beside a config that cannot say
            # which env they load into. (The NTP runs pin their tapes via
            # data_fingerprint; play_ntp asserts it at load.)
            has_sac = any((run_dir / n).exists() for n in CHECKPOINTS)
            findings.append(
                Finding(
                    f"{run_dir.name}: config is readable",
                    not has_sac,
                    "no env_id and SAC checkpoints beside it — which env do they "
                    "load into? The config is broken." if has_sac else
                    "no env_id, no SAC checkpoints — not a SAC run; outside this "
                    "guard's contract, named rather than skipped",
                    n=1,
                )
            )
            continue
        env_id = config["env_id"]

        is_retired = run_dir.name in retired

        try:
            want_obs, want_act = _env_shapes(env_id)
        except Exception as exc:  # a missing asset or an unregistered id
            # A declared orphan whose env genuinely will not build is the
            # declaration coming true, so it passes — and says so loudly enough
            # that nobody mistakes it for a healthy run.
            findings.append(
                Finding(
                    f"{run_dir.name}: env {env_id} builds",
                    is_retired,
                    f"{type(exc).__name__}: {exc}"
                    + (f"  <- retired {retired[run_dir.name].get('retired_at')}, "
                       "as declared" if is_retired else ""),
                    n=1,
                )
            )
            continue

        # The width comparison below only catches a change that RESIZES the
        # observation. A reorder or a redefinition keeps the width and loads
        # cleanly, feeding the policy a permuted world — so compare the
        # recorded spec hash too, when the run has one.
        recorded_spec = config.get("obs_spec")
        spec_matches: bool | None = None  # None = this run predates the spec record
        if recorded_spec is None:
            # Not a failure: these runs predate the spec record. Counted and
            # named rather than skipped, because a silent skip is how a guard
            # reports full coverage it does not have.
            unpinned.append(run_dir.name)
        else:
            pinned.append(run_dir.name)
            try:
                live = _env_obs_spec(env_id)
            except Exception as exc:
                findings.append(
                    Finding(f"{run_dir.name}: {env_id} exposes an obs spec", False,
                            f"{type(exc).__name__}: {exc}", n=1)
                )
                live = None
            if live is not None:
                spec_matches = recorded_spec.get("hash") == live.hash
                if not is_retired:
                    findings.append(
                        Finding(
                            f"{run_dir.name}: obs spec still matches what it recorded",
                            spec_matches,
                            f"recorded {recorded_spec.get('hash')} "
                            f"(width {recorded_spec.get('width')}) vs live {live.hash} "
                            f"(width {live.width})"
                            + ("" if spec_matches else
                               "  <- the observation list changed under this run"),
                            n=1,
                        )
                    )

        loads: dict[str, bool] = {}
        for name in CHECKPOINTS:
            zip_path = run_dir / name
            if not zip_path.exists():
                continue
            checked += 1
            try:
                got_obs, got_act = _checkpoint_shapes(zip_path)
            except (KeyError, zipfile.BadZipFile, json.JSONDecodeError) as exc:
                findings.append(
                    Finding(f"{run_dir.name}/{name}: readable", False,
                            f"{type(exc).__name__}: {exc}", n=1)
                )
                continue

            ok = (got_obs, got_act) == (want_obs, want_act)
            loads[name] = ok
            if is_retired:
                continue  # judged together, below
            findings.append(
                Finding(
                    f"{run_dir.name}/{name} loads into {env_id}",
                    ok,
                    f"checkpoint {got_obs}obs/{got_act}act vs env {want_obs}/{want_act}"
                    + ("" if ok else "  <- this checkpoint is orphaned"),
                    n=1,
                )
            )

        if is_retired:
            # One assertion for the whole run, and it is the INVERSE of the
            # live-run one: the declaration says this is dead, so the guard
            # checks that it really is. A retired run that loads cleanly AND
            # whose spec still matches is a stale declaration — which is the
            # check that stops this file becoming a way to mute the guard.
            # "Dead" is either width incompatibility or a moved spec hash: a
            # reorder at identical width loads fine and feeds the policy a
            # permuted world, which orphans it just as completely.
            dead_by_width = any(not ok for ok in loads.values())
            dead_by_spec = spec_matches is False
            row = retired[run_dir.name]
            head = (
                f"retired {row.get('retired_at')} by {row.get('retired_by')}; "
                f"env {env_id} is {want_obs}obs/{want_act}act; checkpoints "
                + (", ".join(f"{n}={'loads' if ok else 'dead'}"
                             for n, ok in sorted(loads.items())) or "(none readable)")
                + ("; spec unpinned" if spec_matches is None
                   else f"; spec {'matches' if spec_matches else 'moved'}")
            )

            if not loads:
                # Nothing was read, so nothing was judged. This is emphatically
                # NOT "it loads" — saying so would send a 3am operator to delete
                # the one surviving record that learning 003 bit us, on the
                # strength of a load that never happened. record.retire refuses
                # to create such a row, so reaching this state means the .zip
                # files went missing after the fact, and they ARE the run.
                # No remedy here mentions removing the declaration, even to
                # forbid it: the fix is on disk, and a scanned instruction is
                # read by its verbs. `check_checkpoint_width` asserts the word
                # is absent.
                why = (
                    "  <- NO readable checkpoint on disk, so deadness could not be "
                    "verified. Restore this run's .zip files; they ARE the run, and "
                    f"its line in {paths.RETIRED.name} must stay — record.retire "
                    "will refuse to re-create it."
                )
            elif dead_by_width or dead_by_spec:
                why = ""
            else:
                why = (
                    "  <- it LOADS and "
                    + ("its spec matches" if spec_matches is True
                       else "it has no recorded spec to contradict that")
                    + f": this retirement is STALE, delete its line from "
                      f"{paths.RETIRED.name}"
                )

            findings.append(
                Finding(
                    f"{run_dir.name}: orphaned as declared ({row.get('reason', '?')})",
                    bool(loads) and (dead_by_width or dead_by_spec),
                    head + why,
                    n=1,  # this run's declaration, one of those iterated
                )
            )

    if not checked:
        # Quantified over the checkpoints read off disk, which is zero here by
        # construction: VACUOUS is the honest verdict, not PASS.
        findings.append(Finding("checkpoints found", True, "none on disk", n=checked))

    # `runs/` is gitignored and machine-local, so a clone legitimately has none
    # of these directories while still carrying the tracked declarations. Absent
    # is therefore reported, never failed — but it IS reported, because a
    # retirement naming a run nobody can find is how the file rots into fiction.
    absent = sorted(r for r in retired if not (paths.RUNS / r).is_dir())
    if absent:
        findings.append(
            Finding(
                "retired runs are accounted for",
                True,
                f"{len(absent)} declared but not on this machine "
                f"(runs/ is gitignored): {absent}",
                # The checkable set is the declarations whose run IS on disk;
                # the absent ones are named, not verified, so they are excluded.
                n=len(retired) - len(absent),
            )
        )

    # Reported, never silent. Every unpinned run is one whose observation could
    # change without any check noticing, and the number should visibly fall to
    # zero as runs are started under the spec record rather than quietly sit
    # there. It is not a FAIL: these runs are finished, and inventing a spec
    # for them from today's code would be the false provenance this prevents.
    findings.append(
        Finding(
            "every run records the observation spec it trained against",
            True,
            f"{len(unpinned)} run(s) predate the spec record and cannot be "
            f"checked for a width-preserving change: {sorted(unpinned)}"
            if unpinned else "all runs pinned",
            # Only the pinned runs were genuinely verified; the unpinned ones
            # are the uncheckable remainder this finding exists to name.
            n=len(pinned),
        )
    )
    return findings
